### ISSUE TITLE
[Feature request] All-the-icons support

### ISSUE THREAD

**Issue by forkrul** [org-roam/org-roam-server#101]
Doom emacs comes with all-the-icons as a standard inclusion - I sometimes use this in notes, leading to situations like:

![image](https://user-images.githubusercontent.com/190788/96278868-50ec1800-0fd6-11eb-9cb8-7a88e3026ef4.png)

Could icon support be incorporated/stripped to make the web-view cleaner?

**Comment by goktug97** [comment]
I think icons are related to the browser, it is not something I can implement

**Comment by forkrul** [comment]
Perhaps this helps?

https://github.com/domtronn/all-the-icons.el

**Comment by goktug97** [comment]
Unfortunately, to show them in the browser every character should be converted to html version (Ex:  `<i class="fas fa-user"></i>`) and it must be done for every font. I am sorry but I don't have time to implement this functionality.
