### ISSUE TITLE
Enabling org-roam-server adds 8 secs to Emacs opening time

### ISSUE THREAD

**Issue by Bargsteen** [org-roam/org-roam-server#105]
After I enabled org-roam-server Emacs takes 8-10 seconds longer to load (normally it takes 2 sec, so it is a substantial increase).

I am using Doom Emacs (Doom v2.0.9 (HEAD -> develop 664937a3f 2020-10-20 23:25:36 -0400)) on MacOS 10.15.7 and have the following:

**`.doom.d/packages.el`**
```
(package! org-roam-server)
```

**`.doom.d/config.el`**
```
(use-package! org-roam-server
  :ensure t
  :config
  (setq org-roam-server-host "127.0.0.1"
        org-roam-server-port 8080
        org-roam-server-authenticate nil
        org-roam-server-export-inline-images t
        org-roam-server-serve-files nil
        org-roam-server-served-file-extensions '("pdf" "mp4" "ogv")
        org-roam-server-network-poll t
        org-roam-server-network-arrows nil
        org-roam-server-network-label-truncate t
        org-roam-server-network-label-truncate-length 60
        org-roam-server-network-label-wrap-length 20))
```

If I comment out the `use-package` in `config.el`, then the loading time goes back down to 2 sec.

No buffers relating to org-roam-server are running after start-up, and `127.0.0.1:8080` isn't working either, so that does not seem to be the problem.

**Comment by goktug97** [comment]
https://github.com/jschaf/esup can you try this? Maybe it can give a useful information.

**Comment by consoleaf** [comment]
`:ensure t` is not supposed to be used here. You're already ensuring it by putting `(package! org-roam-server)` in your `packages.el`. Might be that your emacs is installing org-roam-server on startup.

**Comment by LesleyLai** [comment]
Have the same situation on my Windows. Benchmarked by esup:

![ESUP benchmark](https://user-images.githubusercontent.com/8359374/99183568-17ecb380-26fa-11eb-88f3-b4db6797fec0.PNG)

**Comment by Bargsteen** [comment]
Turns out that packages are loaded eagerly by default when using `use-package!`.
From [Doom's documentation](https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#packages-are-eagerly-loaded):

> Using use-package! without a deferring keyword (one of: :defer :after :commands :defer-incrementally :after-call) will load the package immediately. This causes other packages to be pulled in and loaded, which will compromise many of Doom’s startup optimizations.

To postpone loading the package until necessary, I added `:after-call org-roam-server-mode`, like so:
```
(use-package! org-roam-server
  :after-call org-roam-server-mode ;; ADD THIS LINE
  :config
  (setq org-roam-server-host "127.0.0.1"
        org-roam-server-port 8282
        org-roam-server-authenticate nil
        org-roam-server-export-inline-images t
        org-roam-server-serve-files nil
        org-roam-server-served-file-extensions '("pdf" "mp4" "ogv")
        org-roam-server-network-poll t
        org-roam-server-network-arrows nil
        org-roam-server-network-label-truncate t
        org-roam-server-network-label-truncate-length 60
        org-roam-server-network-label-wrap-length 20))
```
And now the startup time is back to normal ;)
