### ISSUE TITLE
preview gives 404 error

### ISSUE THREAD

**Issue by JSDurand** [org-roam/org-roam-server#107]
Thanks for the work. This incredibly enhances the usefulness of org-roam, IMHO.

But when using this package I encounter some problems. The first is that it shows a blank page with only 5 buttons. After searching for the issues page, I tried to update doom (and unpin org-roam), and this fixed this issue.

Now it shows the graphs fine, but previewing doesn't work: it shows something like in the attached screen-shot.
<img width="1437" alt="Capture d’écran 2020-10-28 à 20 11 51" src="https://user-images.githubusercontent.com/13595506/97434334-d4542480-1959-11eb-885a-1732071d4453.png">

I tried to run `org-roam-db-build-cache`, and pressed the reload button, but got the same error.

Also `(org-roam-diagnostics)` gives:

```
Copy info below this line into issue:
- Emacs: GNU Emacs 27.1 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.6 (Build 19G2021))
 of 2020-08-28
- Framework: Doom
- Org: Org mode version 9.4 (nil @ /Users/durand/.emacs.d/.local/straight/build/org-mode/)
- Org-roam: 1.2.2

```

If there is something I can do to help diagnose the problem, I would like to do. :-)

**Comment by goktug97** [comment]
Your roam-data is connected to the port 537, which means you are using that port but why your other requests are sent to 8080 port? Can you look into that

**Comment by JSDurand** [comment]
Actually I am using the port 8080. Below is my config (I am using doom emacs by the way).

```emacs-lisp
(use-package! org-roam-server
  :after org-roam
  :config
  (setq org-roam-server-host "127.0.0.1"
        org-roam-server-port 8080
        org-roam-server-authenticate nil
        org-roam-server-export-inline-images t
        org-roam-server-serve-files nil
        org-roam-server-served-file-extensions '("pdf" "mp4" "ogv")
        org-roam-server-network-poll t
        org-roam-server-network-arrows nil
        org-roam-server-network-label-truncate t
        org-roam-server-network-label-truncate-length 60
        org-roam-server-network-label-wrap-length 20)
  (org-roam-server-mode))
```
I examined my config files, and the only place which mentions 537 is in a sha number of git file, that is, my configs don't contain this number at all. I don't know why it is connected to that port.

And I tried to set the port to 537, and then restart emacs. But I cannot connect to 127.0.0.1:537 for some reason. And I can still connect to 127.0.0.1:8080, but that shows a blank screen with 5 buttons.

I am not sure where the problem resides. Do you have any clue as to what the possible causes are? Thanks in any case for the attention.

**Comment by goktug97** [comment]
Can you try 
- copy paste one of the 404 links 
- change the port manually to 537
- go to that link

Does it show anything?

**Comment by JSDurand** [comment]
Well, something strange happens.

When I open 127.0.0.1:8080 from Safari, there actually are some errors: those errors about bootstrap and vis-network in the above picture. If I copy the link and change the port to 537, then Safari complains that it cannot connect to the server 127.0.0.1.

However, I tried to enable the preview once again, and this time it mysteriously works! I don't remember changing anything though...

So I guess unless the errors about some javascript not loaded are potentially serious, we can close the issue?
Thanks for your responses. :D

**Comment by goktug97** [comment]
Yes they are not important errors. The files that are missing are just required for debugging purposes

**Comment by JSDurand** [comment]
OK, then we can happily close the issue, though I don't know what happened. XD
Your responses are much appreciated. :-)
