### ISSUE TITLE
Cannot preview note infos when there are images

### ISSUE THREAD

**Issue by nicehiro** [org-roam/org-roam-server#108]
Hi, your work is really great!

The image cannot be loaded completely.

Here are some images about chrome Network information.
![image](https://user-images.githubusercontent.com/17773634/97773375-2a0f1380-1b8a-11eb-8609-c3df59ce6c6c.png)

![image](https://user-images.githubusercontent.com/17773634/97773379-32ffe500-1b8a-11eb-98c3-6fa2be6ff81a.png)

I google it and find this one maybe help:
https://stackoverflow.com/questions/45816743/how-to-solve-this-caution-request-is-not-finished-yet-in-chrome

But I'm not good at js... Hope you could help me solve this problem.

 Thank you.

**Comment by goktug97** [comment]
Are you using the latest version? Also can you try different browser to see if it makes any difference

**Comment by nicehiro** [comment]
> Are you using the latest version? Also can you try different browser to see if it makes any difference

Emmm, you are right.
I update org-roam and org-roam server, everything is perfect!

Thank you!
