### ISSUE TITLE
error: (emacsql-error near line 167: no such column: dest)

### ISSUE THREAD

**Issue by aerojustaero** [org-roam/org-roam-server#109]
Looks like version of org-roam-server on melpa uses other db scheme than org-roam version does.

**Comment by goktug97** [comment]
Are you using doom emacs? I don't really know doom emacs but some users do something like `unpin` to update their org-roam. org-roam and org-roam-server is updated at the same time for the new db version

**Comment by aerojustaero** [comment]
got it , 
yes doom emacs 
and (unpin! org-roam) works well 

thanks
