### ISSUE TITLE
Allow port configuration of the server

### ISSUE THREAD

**Issue by davidpham87** [org-roam/org-roam-server#11]
Hello,

The server will automatic bind to 127.0.0.1:8080. Do you think it would be to much work to make the port configurable?

Thanks a lot :-)

**Comment by goktug97** [comment]
I think some of the variables should be extracted and exposed to the user as a custom variable. I don't know which ones yet but this can be one of them.
You can also set the server port using `simple-httpd` directly before starting the server.
```elisp
(require 'simple-httpd)
(setq httpd-port 8888)
```
but it would be much more convenient with a custom variable.

**Comment by davidpham87** [comment]
Thanks for the answer! I guess this is enough for my use case :-)

**Comment by goktug97** [comment]
Added port as a customizable variable.
For example;

```elisp
(use-package org-roam-server
  :ensure t
  :config (setq org-roam-server-port 8888))
```
