### ISSUE TITLE
error: (emacsql-error near line 3193: no such column: dest)

### ISSUE THREAD

**Issue by aviaviavi** [org-roam/org-roam-server#110]
👋 

Just tried installing org-roam-server with the use-package command in the readme. When I hit the page in my browser, my network and file viewer are empty, reloading the org-roam db cache doesn't have any effect, nor does the reload button on the page. I see the server is returning a 500 to the browser, `error: (emacsql-error near line 3193: no such column: dest)`. 

I ran `server-start` in emacs as well, and my org-roam can generate a graph just fine. Let me know what other details are useful here for troubleshooting. 

Thanks for the work going into this project, really excited to use it!

**Comment by goktug97** [comment]
> Thanks for the work going into this project, really excited to use it!

Thanks!!

Update `org-roam`

**Comment by aviaviavi** [comment]
Thank you - I thought I had done that actually, missed the fact that the update failed. Working now!
