### ISSUE TITLE
Last update gives database linking issues

### ISSUE THREAD

**Issue by forkrul** [org-roam/org-roam-server#111]
Org-roam seems to have upgraded the database, and since then I cannot get the interface to load. 

On running developer tools on http://localhost:8080/roam-data?force=1&token=null I get:

"500 Internal Error
Internal error when handling this request.

error: (emacsql-error near line 45: no such column: links.to)"

Is there something I can run, update to fix this?

**Comment by goktug97** [comment]
You should update your `org-roam-server`

**Comment by forkrul** [comment]
Thanks, what the standard mechanism for doing this?

Typically with doom one would doom sync and upgrade, and the necessary new packages would be pulled.  I could package delete, and package install this, but would prefer to embed this to automatically get updated to the latest version. 

Currently I just have 

`#+BEGIN_SRC emacs-lisp
(use-package org-roam-server
  :config
  (setq org-roam-server-host "127.0.0.1"
        org-roam-server-port 8080
        org-roam-server-authenticate nil
        org-roam-server-export-inline-images t
        org-roam-server-serve-files t
        org-roam-server-served-file-extensions '("pdf" "mp4" "ogv")
        org-roam-server-network-poll nil
        org-roam-server-network-arrows nil
        org-roam-server-network-label-truncate t
        org-roam-server-network-label-truncate-length 60
        org-roam-server-auto-update nil
        org-roam-server-network-label-wrap-length 20))
#+END_SRC
`
in my literate conf /.doom.d/config.org - is there something else I should be doing instead?

**Comment by goktug97** [comment]
Unfortunately I don't know how doom emacs packaging system works but people do `unpin` to update their packages sometimes

**Comment by forkrul** [comment]
Thanks, will see if I find more information.
