### ISSUE TITLE
unable to get org-roam-server to work on either macos or ubuntu 20.04

### ISSUE THREAD

**Issue by emacs18** [org-roam/org-roam-server#112]
I am unable to get org-roam-server to work on either ubuntu 20.04 or macos (Catalina).
I hope that someone can help me resolve the remaining issues to get me going.
I would like to setup org-roam and org-roam-server on both spacemacs and doom for my colleagues at work.

On my ubuntu 20.04 laptop, I use emacs 27 and 28 which I build from source once every few weeks. I use latest spacemacs develop branch. I use firefox as my web browser.

I was able to get org-roam-server to work well enough to display a colorful diagram of my org files, i.e., firefox displayed colorful diagram with circles and lines between them.  However nothing else seem to work.  Clicking on any circle or line does nothing.  Clicking on "File Viewer" shows nothing.

How do I debug this?  I've been hacking on elisp for decades, so I can handle elisp, but I don't know much about web stuff like javascript, css, etc. 

On macos the web page seem to start up since I can see few buttons such as "Database network", "Buffer network", etc.
However, but nothing else is displayed, i.e., no circles and no lines.  I started out using emacs 27 from emacsformacos web site, then switched over to the version from https://github.com/railwaycat/homebrew-emacsmacport.  The primary reason was to get org-roam-graph to work.

If org-roam-server can be made to work on centos 6 or 7, that would be great, because that is what I need to use at work.

**Comment by goktug97** [comment]
Does the console in Firefox output anything?

**Comment by emacs18** [comment]
Do you mean a dialog box that pops up titled "Browser Console"?  The last few errors that I find there are quoted below. 

1605375606656	Toolkit.Telemetry	ERROR	TelemetrySend::_sendWithPingSender - failed to submit ping: [Exception... "Component returned failure code: 0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST) [nsIProcess.init]"  nsresult: "0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST)"  location: "JS frame :: resource://gre/modules/TelemetrySend.jsm :: runPingSender :: line 1595"  data: no] Stack trace: runPingSender()@resource://gre/modules/TelemetrySend.jsm:1595
_sendWithPingSender()@resource://gre/modules/TelemetrySend.jsm:986
submitPing/<()@resource://gre/modules/TelemetrySend.jsm:1022 Log.jsm:723
Sync encountered an error - see about:sync-log for the log file. policies.js:996
    resetFileLog resource://services-sync/policies.js:996
    InterpretGeneratorResume self-hosted:1468
    AsyncFunctionNext self-hosted:674
1605375607039	Toolkit.Telemetry	ERROR	TelemetrySend::_doPing - error making request to https://incoming.telemetry.mozilla.org/submit/telemetry/71de16de-2bad-4b36-a30c-4540175931a1/main/Firefox/82.0.3/release/20201108180448?v=4: eUnreachable Log.jsm:723
    append resource://gre/modules/Log.jsm:723
    log resource://gre/modules/Log.jsm:379
    log resource://gre/modules/Log.jsm:508
    error resource://gre/modules/Log.jsm:387
    errorhandler resource://gre/modules/TelemetrySend.jsm:1361

**Comment by goktug97** [comment]
![image](https://user-images.githubusercontent.com/20567087/99153924-f4574800-26bc-11eb-802f-d4fcd8176a00.png)
`Ctrl+Shift+K` on Firefox. Also you should be in the `org-roam-server` tab.

**Comment by emacs18** [comment]
I see.   I see the following.  When I clicked on a circle, firefox brought up a pop-up saying something like "http://127... wants to open a org-protocol link, so I just accepted the default choice of "Org-Protocol".

```
Prevented navigation to “org-protocol://roam-file?file=%2Fhome%2Fkimr%2Fkimr%2Forg%2Fpython%2Fpython.org” due to an unknown protocol. 127.0.0.1:8080
Prevented navigation to “org-protocol://roam-file?file=%2Fhome%2Fkimr%2Fkimr%2Forg%2Freal-estate%2Frealtor.org” due to an unknown protocol.
```

I followed the instruction I found by typing the following.
```
$ xdg-mime default org-protocol.desktop x-scheme-handler/org-protocol
$ cat ~/.local/share/applications/org-protocol.desktop
[Desktop Entry]
Name=Org-Protocol
Exec=emacsclient %u
Icon=emacs-icon
Type=Application
Terminal=false
MimeType=x-scheme-handler/org-protocol
$ 
```

**Comment by emacs18** [comment]
Let me make sure that I am using correct emacsclient.
I has trying both emacs 27 and 28 to see if I could get one to work.
As of now I may be using emacs 28, but "emacsclient" in my PATH may be one from emacs 27.
Perhaps that is the problem now.  Let me at least make sure that my emacs and emacsclient match up

**Comment by goktug97** [comment]
What does it show when you clicked to `File Preview` and choose a file?

**Comment by emacs18** [comment]
Nothing.  I tried clicking on all the buttons, but nothing shows up.  No text whatsoever.

**Comment by emacs18** [comment]
This is what I find in the console.

```
Firefox can’t establish a connection to the server at http://127.0.0.1:8080/current-buffer-data?token=null. 127.0.0.1:8080:513:30
Firefox can’t establish a connection to the server at http://127.0.0.1:8080/roam-data?token=null. 127.0.0.1:8080:541:31
```

**Comment by emacs18** [comment]
I am now running emacs 27 rather than 28.  Typing "which emacsclient" shows that emacsclient is the matching version of emacs that I built.  Still I see no change in behavior.

**Comment by goktug97** [comment]
Can you check your `org-roam` version by running `org-roam-version`

**Comment by emacs18** [comment]
Value is 10.  I'm pretty sure all my emacs packages are up to date, because I built them all yesterday.  Rather than using internet ELPA archives, I use my own ELPA archives, e.g., rather than using melpa, I use https://github.com/emacs18/melpa-packages which I build myself.

**Comment by goktug97** [comment]
The output of the function should be `1.2.3`. Does your notes have connections?

**Comment by emacs18** [comment]
Sorry I incorrectly assumed you meant variable whose value is 10.
The function returns 1.2.3.

**Comment by emacs18** [comment]
What do you mean by connections?
When I run org-roam-graph, a diagram pops up an svg file on my firefox with boxes and arrows between boxes.
Is that what you mean?

**Comment by goktug97** [comment]
Can you enable preview by clicking the `Enable Preview` button in the top left corner and hover on to one of the nodes. Does it show anything? Also keep firefox `Console` open to see if it outputs anything.

**Comment by emacs18** [comment]
An error message pops up saying
```
500 Internal Error

Internal error when handling this request.

error: (user-error Unable to resolve link: "el:Sequences Arrays Vectors")
```

**Comment by emacs18** [comment]
Firefox console had this
```
The character encoding of a framed document was not declared. The document may appear different if viewed without the document framing it. elisp.html
```

**Comment by emacs18** [comment]
Console had this when I clicked on a circle:
```
Loading failed for the <script> with source “http://127.0.0.1:8080/real-estate/styles/readtheorg/js/readtheorg.js”.
```
It also mentioned "realtor.html".  Does org-roam-server automatically convert realtor.org into realtor.html on the fly?  Am I supposed to generate HTML files myself?

**Comment by emacs18** [comment]
My org files have this line near the top:
```
#+SETUPFILE: ~/public_html/org-html-themes/setup/theme-readtheorg-local.setup
```
Perhaps this is getting in the way.

**Comment by emacs18** [comment]
That was it!  When I comment it out, then I started seeing my text!

**Comment by goktug97** [comment]
> An error message pops up saying
> 
> ```
> 
> 500 Internal Error
> 
> 
> 
> Internal error when handling this request.
> 
> 
> 
> error: (user-error Unable to resolve link: "el:Sequences Arrays Vectors")
> 
> ```

This means there is an error happening in the server (emacs)

**Comment by goktug97** [comment]
> That was it!  When I comment it out, then I started seeing my text!
> 
> 

Everything is working now then?

**Comment by emacs18** [comment]
Next I'm going to comment out all my  `#+SETUPFILE:` lines and see how it works.
Thanks a lot for your help.  I'll get back and report how I'm doing in a few hours.
It appears that things are working now.

**Comment by emacs18** [comment]
Actually `#+SETUPFILE:` was not the problem.  My problem was that my org files had many invalid links, e.g., `[[foo]]` when there was no headline titled "foo".  Once I fixed this, I now get pop-ups of the file content when mouse pointer hovers over a circle.  This is of course with the preview mode enabled.

When I click on `Buffer Network` button on upper right, it seems to show a subset of what is shown with `Database Network` in that nodes connected to "current" file are shown only.  Clicking on other circles seem to change the current buffer.  I assume this is how it is supposed to work.  Also changing "Distance" from 1 to 2 shows more circles as expected.

When I click on `File Viewer` button on upper right, I still get nothing.  clicking on `Back`, `Edit`, and `Refresh` buttons on upper left seems to do nothing.  The value of `org-roam-server-serve-files` is `t` if that matters.

On org-roam-server home page, the animation seems to show that clicking on circles bring up corresponding file in emacs.  Is this really the case?  If so, what do I need to do to enable that feature?

**Comment by goktug97** [comment]
> On org-roam-server home page, the animation seems to show that clicking on circles bring up corresponding file in emacs. Is this really the case? If so, what do I need to do to enable that feature?

When the `org-protocol` is set, it will work automatically. 

> When I click on File Viewer button on upper right, I still get nothing. clicking on Back, Edit, and Refresh buttons on upper left seems to do nothing. The value of org-roam-server-serve-files is t if that matters.

There is no dropdown menu in the top left corner?

**Comment by emacs18** [comment]
Ah.  I did not even notice that there was this "File" button!
Yes clicking on this allows me to select a file, and doing so displays the content of that file.
I think I have become GUI challenged after having using emacs for 30+ years with toolbar/menubar/toolbar disabled.
Thanks again.

I'm looking into this org-protocol thing now.  Hopefully I can figure out soon.

**Comment by emacs18** [comment]
I am still unable to get the `Edit` button to work in `File Viewer`.  It appears to me that `index.html` is supposed to invoke `emacsclient` and pass  `org-protocol://roam-file` argument along with file path.  In response emacs is supposed to open the specified file.  Is this correct understanding?

If so, then the problem seems to be that `emacsclient` is not called.  I say this based on two observations.  First when I type 
```
emacsclient org-protocol://roam-file?file=/u/me/org/top.org
```
shell command, then my emacs pops up the specified file.  Thus my emacs has the server running, and `org-protocol-protocol-alist` setup to handle `roam-file` protocol.  Second I added the following line at the start of `org-roam-protocol-open-file` function:
```
(message "(my) org-roam open file %s" info)
```
so that I can tell whether this function is called or not.  When I manually invoke `emacsclient` as detailed above, then this message is printed.  However clicking on `Edit` button does not print anything.

What can I do to further debug this?

**Comment by goktug97** [comment]
Does clicking on a node in `Database Network` tab open the corresponding file?

**Comment by emacs18** [comment]
No.

**Comment by goktug97** [comment]
It seems your `org-protocol` still has some problems can you try clicking on a node in the graph that is generated by `org-roam-graph` so we can be sure it is not a problem directly related to the `org-roam-server` itself

**Comment by emacs18** [comment]
`org-roam-graph` brings up url such as `file:///tmp/graph.NUSMFH.svg` on my firefox.
None of the boxes seem to be clickable.  I had no idea that these were supposed to be clickable.

**Comment by emacs18** [comment]
On firefox if I hover over one of the boxes of the graph produced by `org-roam-graph`, then firefox displays URL's auch as `org-protocol://roam-file?file=%2Fhome%2Fme%2Forg%2Femacs%2Femacs.org`.  If I ask firefox to save this url to clipboard, then manually issue the following command, then the proper org file pops up in my emacs:

```
emacsclient 'org-protocol://roam-file?file=%2Fhome%2Fme%2Forg%2Femacs%2Femacs.org'
```

Thus it appears that my firefox seems to be missing something. It does not seem to be issuing emacsclient command.

**Comment by emacs18** [comment]
It is working now.  Clicking on files for both `org-roam-graph` output as well as `org-roam-server` output now bring up the file in my emacs.  It appears that the following command needed to be issued again.

```
xdg-mime default org-protocol.desktop x-scheme-handler/org-protocol
```
Do I need to issue this command each time I login?

**Comment by emacs18** [comment]
@goktug97 
Thank you very much for all your help.  It looks like all features are working on my ubuntu laptop.
Now I'm motivated to learn and use org-roam and org-roam-server for all my org files.
I will be splitting up my org files so that `Preview` mode can display files under 5 seconds.

I plan on writing up org-roam and org-roam-server to help explain these packages to my colleagues.  Perhaps I can help with documenting these packages in the future.

**Comment by goktug97** [comment]
Awesome!! I am happy to hear everything is working
