### ISSUE TITLE
void-function org-roam-db--get

### ISSUE THREAD

**Issue by jacklisp** [org-roam/org-roam-server#125]
when I type "M-x org-roam-server-mode"，I got this error show in minibuffer:
  Debugger entered--Lisp error: (void-function org-roam-db--get)
  org-roam-db--get()
...

I didn't found the org-roam-db--get method in 
https://github.com/org-roam/org-roam/blob/master/org-roam-db.el
May be the org-roam package has changed this method name.
Counld any body fix this? Thanks

**Comment by goktug97** [comment]
It is removed from `org-roam-server` too when it is removed from `org-roam`. You should update your package

https://github.com/org-roam/org-roam-server/commit/1dc94e102d60e53bb9929b1cdc55d4d8c2b0d64f

**Comment by jacklisp** [comment]
update the org-roam-server package can fix this problem, Thanks a lot!
