### ISSUE TITLE
Output encoding

### ISSUE THREAD

**Issue by forkrul** [org-roam/org-roam-server#13]
First absolutely great tool, super helpful for weekly consolidating of notes, and free roaming. Thanks for building this. 

**Issue**: I seem to be seeing output encoding as is &amp; instead of & (as intended) in the graphs. As I use a lot of & and apostrophes, so this seems to turn up everywhere.

![image](https://user-images.githubusercontent.com/190788/82484296-03788700-9ada-11ea-9aaa-a74542ecb40c.png)

**Comment by goktug97** [comment]
> First absolutely great tool, super helpful for weekly consolidating of notes, and free roaming. Thanks for building this.

Thank you!

https://github.com/org-roam/org-roam-server/commit/74eeaba698de677161890d3d78920d8bba1a79d0 It should be fixed now.
Can you test it

**Comment by forkrul** [comment]
Works perfectly. And darkmode. Is it christmas already?
