### ISSUE TITLE
error: (wrong-type-argument arrayp nil) in File Viewer if file have backlink

### ISSUE THREAD

**Issue by tshu-w** [org-roam/org-roam-server#132]
I got the following error in File Viewer if the file has backlinks. However, everything seems to work fine in Emacs.
toggle-debug-on-error don't give me any backtrace.
```
500 Internal Error

Internal error when handling this request.

error: (wrong-type-argument arrayp nil)
```
<img width="1380" alt="Screen Shot 2021-01-24 at 10 23 12 PM" src="https://user-images.githubusercontent.com/13161779/105633298-c186b880-5e92-11eb-9917-46196c4557cf.png">

The minimum config:
```emacs-lisp
;;; emacs -nw -Q -l ~/.emacs.d/test.el

(setq package-archives '(("melpa"        . "https://melpa.org/packages/")
                         ("melpa-stable" . "https://stable.melpa.org/packages/")
                         ("org"          . "https://orgmode.org/elpa/")
                         ("gnu"          . "https://elpa.gnu.org/packages/"))
      package-user-dir (concat user-emacs-directory "elpa/"
                               (format "%d%s%d"
                                       emacs-major-version
                                       version-separator
                                       emacs-minor-version)))

;; initialize packages
(unless (bound-and-true-p package--initialized) ; To avoid warnings in 27
  (setq package-enable-at-startup nil)          ; To prevent initializing twice
  (package-initialize))

;; setup `use-package'
(unless (package-installed-p 'use-package)
  (when (not package-archive-contents)
    (package-refresh-contents))
  (package-install 'use-package))

(require 'use-package)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(use-package org-roam
  :ensure t
  :init
  (setq org-roam-capture-templates
        '(("d" "default" plain (function org-roam-capture--get-point)
           "%?"
           :file-name "${slug}"
           :head "#+title: ${title}\n#+created: %<%Y%m%d>\n"
           :unnarrowed t))
        org-roam-db-gc-threshold most-positive-fixnum
        org-roam-tag-sources '(prop all-directories))
  :config
  (org-roam-mode))

(use-package org-roam-protocol :after org-protocol)

(use-package org-roam-server
  :ensure t
  :config
  (defun open-org-roam-server()
    "Enable `org-roam-server-mode' and open link"
    (interactive)
    (unless (bound-and-true-p org-roam-server-mode)
      (org-roam-server-mode))
    (browse-url
     (format "http://%s:%d" org-roam-server-host org-roam-server-port))))
```

GNU Emacs 28.0.50 (build 2, x86_64-apple-darwin20.2.0, NS appkit-2022.20 Version 11.1 (Build 20C69)) of 2021-01-16

**Comment by goktug97** [comment]
I can't see any problem in your config. I tried your config with the latest version of `org-roam` and couldn't reproduce the error.

**Comment by tshu-w** [comment]
@goktug97 Strangely enough, I tried emacs 27 or 28, the latest version of packages, even with only two files and one link, and the problem persists.

**Comment by goktug97** [comment]
Do you have any org export setting that might be affecting it?

**Comment by tshu-w** [comment]
maybe not, option `-Q` equal to `-q --no-site-file --no-site-lisp --no-splash --no-x-resources` so all my config is above.

**Comment by Imymirror** [comment]
I have the same problem. at the same time,  the roam server preview display abnormal

![image](https://user-images.githubusercontent.com/52570325/105672966-423fc600-5f20-11eb-9dbc-334168028672.png)

**Comment by nickali** [comment]
I'm having the same 500 internal error issue in File Viewer.

I'm on macOS 11.1 using [emacs-plus@27.1](https://github.com/d12frosted/homebrew-emacs-plus). I've tried a [couple](https://bitbucket.org/mituharu/emacs-mac/src/master/) [other](https://github.com/hlissner/doom-emacs) formulas and they both show the same error. 

If I do C-x C-e after the 500 error, it doesn't show any errors. 

The call to retrieve the backlinks is like:

```http://127.0.0.1:8078/org-roam-buffer?path=/Volumes/192.168.1.111/orgroam/Entertainment.org&label=Entertainment&token=null```

The content of the node with the backlinks looks like this:

```lisp
#+title: Entertainment

Everything should point here.
```
And the content of an edge looks like:
```lisp
#+title: Movies

The Big Lebowski (1998)

[[file:Entertainment.org][Entertainment]]
```
All the .org files are in the same directory.

**Comment by goktug97** [comment]
> I'm having the same 500 internal error issue in File Viewer.
> 
> 
> 
> I'm on macOS 11.1 using [emacs-plus@27.1](https://github.com/d12frosted/homebrew-emacs-plus). I've tried a [couple](https://bitbucket.org/mituharu/emacs-mac/src/master/) [other](https://github.com/hlissner/doom-emacs) formulas and they both show the same error. 
> 
> 
> 
> If I do C-x C-e after the 500 error, it doesn't show any errors. 
> 
> 
> 
> The call to retrieve the backlinks is like:
> 
> 
> 
> ```http://127.0.0.1:8078/org-roam-buffer?path=/Volumes/192.168.1.111/orgroam/Entertainment.org&label=Entertainment&token=null```
> 
> 
> 
> The content of the node with the backlinks looks like this:
> 
> 
> 
> ```lisp
> 
> #+title: Entertainment
> 
> 
> 
> Everything should point here.
> 
> ```
> 
> And the content of an edge looks like:
> 
> ```lisp
> 
> #+title: Movies
> 
> 
> 
> The Big Lebowski (1998)
> 
> 
> 
> [[file:Entertainment.org][Entertainment]]
> 
> ```
> 
> All the .org files are in the same directory.

I'll try it with your examples.

**Comment by goktug97** [comment]
Fixed https://github.com/org-roam/org-roam-server/commit/2093ea5a1a1f2d128dd377778472a481913717b4

**Comment by nickali** [comment]
@goktug97 the fix is working for me!

**Comment by tshu-w** [comment]
@goktug97 Thx, it works!.
