### ISSUE TITLE
Feature request: Find and highlight current note on graph

### ISSUE THREAD

**Issue by thriveth** [org-roam/org-roam-server#133]
I love Org-roam-server and its graph view, thanks for the work of putting this together! 

When working with roam and the graph, I often find myself wanting to locate and select the current note in the graph.  With a couple hundred notes and a large amount of links criss-crossing them, this is probably my most narrow bottleneck in my org-roam and server back-and-forth work and often I simply just give up because it is not worth the time and effort, but it would be so incredibly nice and useful to be able to do. 

Perhaps even an Obsidian-like follow-mode, where the local graph of the current note is always shown in the graph view?

**Comment by goktug97** [comment]
Buffer network view follows the current note that is opened in the emacs.

**Comment by thriveth** [comment]
Oh stupid me, how could I have missed that? 
Sorry about the noise!
