### ISSUE TITLE
broadcast to an intranet?

### ISSUE THREAD

**Issue by cryoguy** [org-roam/org-roam-server#136]
Is it possible to broadcast to an intranet?

**Comment by Hellseher** [comment]
Hi,
As you can see the `org-roam-server` is exposed on local host if you follow the example provided in README

_.dom.d/config.el_
```
(use-package! org-roam-server
  :after org-roam
  :config
  (setq org-roam-server-host "127.0.0.1"
        org-roam-server-port 8080
        org-roam-server-authenticate nil
        org-roam-server-export-inline-images t
        org-roam-server-serve-files nil
        org-roam-server-served-file-extensions '("pdf" "mp4" "ogv")
        org-roam-server-network-poll t
        org-roam-server-network-arrows nil
        org-roam-server-network-label-truncate t
        org-roam-server-network-label-truncate-length 60
        org-roam-server-network-label-wrap-length 20)
  (org-roam-server-mode 1))
```
I suppose you have basic knowledge on how to setup your broadband router to portforward specific ports
- you need a reverse proxy (Nginx or Apache or Cady)
  - https://caddyserver.com/docs/quick-starts/reverse-proxy
  - https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/
  - https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html
- you need to forward port 80 (HTTP) and 443 (HTTPS) from your router to your machine/server running `org-roam-sever`
  - https://www.tp-link.com/us/support/faq/72/
  - https://docs.netgate.com/pfsense/en/latest/recipes/port-forwards-from-local-networks.html
  - https://support.zen.co.uk/kb/Knowledgebase/ZyXEL-VMG1312-VMG8924-Port-Forwarding
  
 ```
  [router][80,443] --> [80,443][nginex] --> [8080][localhost]
```

**Comment by cryoguy** [comment]
I  just wanted to access it from another computer at my home.  say if my org-roam-server resides on a local IP 192.168.1.125, and I want to access from my iPad at 192.168.1.125:8080.

**Comment by Hellseher** [comment]
I think this could be a solution

change
```org-roam-server-host "127.0.0.1"```

to
```org-roam-server-host "0.0.0.0"```

**Comment by cryoguy** [comment]
That works.  Thanks!!
