### ISSUE TITLE
Dark mode readibility

### ISSUE THREAD

**Issue by das-s** [org-roam/org-roam-server#14]
First of all, thanks for the great package! I really like the possibility to get an overview and also the  new dark mode is a valuable addition.

Sadly, readibility due to low contrast for congested areas on my screen (1080p) in dark mode is often low, especially when zoomed out.
Here is a comparison between both light and dark mode for roughly the same area:
![2020-05-22-191449_379x211_scrot](https://user-images.githubusercontent.com/47145187/82693084-64c26680-9c50-11ea-87cb-dcbbb999e7af.png)
![2020-05-22-191503_418x225_scrot](https://user-images.githubusercontent.com/47145187/82693092-6724c080-9c50-11ea-88ef-c59d0ce37819.png)

May I suggest a lighter grey or plain white for easier readibility?

**Comment by goktug97** [comment]
Yes it really looks bad.

I updated it. Thank you! https://github.com/org-roam/org-roam-server/commit/0e4ac9ba64c0c3effd0b3baeaaf84bf2369e2c76

What do you think

![image](https://user-images.githubusercontent.com/20567087/82697268-41f47a00-9c71-11ea-8063-4b189213ece1.png)

**Comment by das-s** [comment]
Perfect, thanks for the quick fix!
