### ISSUE TITLE
Add extra-options for the cite-edge as well

### ISSUE THREAD

**Issue by yaqihou** [org-roam/org-roam-server#147]
First of all, thanks a lot for this awesome project!

Could I suggest one extra custom variable to control the style of cite-edges? It is to be added [here](https://github.com/org-roam/org-roam-server/blob/2122a61e9e9be205355c7e2c1e4b65986d6985a5/org-roam-server.el#L371) with a similar name like `org-roam-server-extra-edge-cite-options`? To me, such a need arises as I am trying to distinguish the cite edge from the normal links by making cite edges dashed lines.

I would be glad to create a pull request for this if this looks like good customization to have.

**Comment by ThomasJorna** [comment]
Wow great suggestion! I just quickly implemented it and it works like a charm!

![image](https://user-images.githubusercontent.com/21983833/116689274-6a1f4980-a9a7-11eb-92de-1964c2c33772.png)

I simply added the `(cons 'dashes t)` line to the `dolist`
```emacs-lisp
      (dolist (edge edges-cites)
        (let* ((title-source (org-roam--path-to-slug (elt edge 0)))
               (title-target (org-roam--path-to-slug (elt edge 1))))
          (push (remove nil (list (cons 'from title-source)
                                  (cons 'to title-target)
                                  (cons 'arrows org-roam-server-network-arrows)
                                  (cons 'dashes t)))
                (cdr (elt graph 1)))))
```

I will put together a pull request to define a variable for this. In theory we could also have this be customized even further, but for now the dashes are good enough I think.

**Comment by yaqihou** [comment]
Related pull requenst merged
