### ISSUE TITLE
Is it possible to add a feature like filtering?

### ISSUE THREAD

**Issue by qlibp** [org-roam/org-roam-server#15]
Great work and huge thanks!!!

Looking forward to a feature that enables us to filter our notes on graph!

Or are there some tricks that could work around for now?

**Comment by goktug97** [comment]
Can you give an example

**Comment by qlibp** [comment]
I find it helpful to filter the graph via the titles of the notes and for now it fits my need. If i got  any new ideas, i would add additional comment here!
