### ISSUE TITLE
Title of node

### ISSUE THREAD

**Issue by qlibp** [org-roam/org-roam-server#16]
**situation**: If I enter an quite long notes title, then the name of the node is something like this. 
<img width="1424" alt="屏幕快照 2020-05-23 下午3 11 49" src="https://user-images.githubusercontent.com/43082379/82724315-c1348d00-9d07-11ea-999e-3c751d16fce6.png">

**feature request**: It would be better if there is a param we could set the max length of the name in one line shown in the graph. 

This feature is shown below, implemented by roam research
![屏幕快照 2020-05-23 下午3 08 51](https://user-images.githubusercontent.com/43082379/82724302-9813fc80-9d07-11ea-9caa-31e1ca6b6a08.png)

**Comment by goktug97** [comment]
Added these.
https://github.com/org-roam/org-roam-server/blob/1ac94495294b93786e796fcc5b58a53e8435da02/org-roam-server.el#L70-L80

**Comment by qlibp** [comment]
Further question, I'm not so familiar with emacs system, I just write newly adderd code into **org-roam-server.el** file as mentioned above, but it seems not work. What further steps should I take to activate it?

<img width="1440" alt="屏幕快照 2020-05-23 下午9 03 08" src="https://user-images.githubusercontent.com/43082379/82731624-e262a100-9d3a-11ea-92d9-293b59d2dd44.png">

Thanks!

**Comment by goktug97** [comment]
You don't need to add them yourself. They are added to the Github repo and built by the MELPA. So an update would suffice.
To update the package;
Either open `M-x package-list-packages RET` and press `I` then `x` to update all upgradable packages. Or you can reinstall `org-roam-server` using `package-reinstall`. `M-x package-reinstall RET` and choose `org-roam-server`

**Comment by qlibp** [comment]
Thanks, I'm done!
