### ISSUE TITLE
Is there a way to change the default HTTP port?

### ISSUE THREAD

**Issue by jagross** [org-roam/org-roam-server#17]
I'm really enjoying using this code in my org-roam setup.

I'm working on a website, and I debug changes to the website on a localhost web server running on port 8080. It would be nice if I could change the HTTP port for the org-roam-server to something other than 8080 so I can use both at the same time.

Is there a way to do this?

Thanks!

**Comment by goktug97** [comment]
Yes, you can set `httpd-port` before starting the server.
```elisp
(require 'simple-httpd)
(setq httpd-port 8888)
```
https://github.com/org-roam/org-roam-server/issues/11

**Comment by jagross** [comment]
Thank you!

**Comment by goktug97** [comment]
Added port as a customizable variable.
For example;
```elisp
(use-package org-roam-server
  :ensure t
  :config (setq org-roam-server-port 8888))
```
