### ISSUE TITLE
Needs a way to authenticate clients

### ISSUE THREAD

**Issue by jgoerzen** [org-roam/org-roam-server#18]
As it is, any local process (including web browsers), whether owned by the org-roam-server user or not, can access all of the org-roam data.  This poses a fairly significant security risk, especially on multiuser systems.  HTTP authentication would (hopefully? I don't know how to do this in elisp) be fairly trivial to implement and could help out here.

**Comment by goktug97** [comment]
org roam data is not accessible. The data is served as HTML.

**Comment by jgoerzen** [comment]
Hi Göktuğ,

Thanks for your reply (and your work on this project - it's fantastic)!

So I know that the underlying data can't be modified.  However, there's a lot of sensitive data in my org-roam collection -- even in just the titles.  My concern is that anything with access to the local machine -- which can include other users, other processes, and even other things within the web browser process itself -- could see and copy all that sensitive information.

If you use [HTTP basic authentication](https://en.wikipedia.org/wiki/Basic_access_authentication) or, better, [HTTP digest authentication](https://en.wikipedia.org/wiki/Digest_access_authentication), you need not implement login/logout/cookies on your end.  Just a check for an accurate authorization header, and an appropriate HTTP header if it's missing.

You could of course go the more conventional form/cookie route also, but HTTP auth is often easier to just pop in.

**Comment by goktug97** [comment]
> and your work on this project - it's fantastic

Thank you!

Okay then, I will try to implement the authentication when I have time. If anyone is interested I would also appreciate a pull request.

**Comment by goktug97** [comment]
I added an authentication system. I don't know if it is the "correct" way to do this but it is working.
You can enable authentication by setting `org-roam-server-authenticate` to `t`.

**Comment by jgoerzen** [comment]
That looks great.  Thanks!
