### ISSUE TITLE
Make port configurable

### ISSUE THREAD

**Issue by jgoerzen** [org-roam/org-roam-server#19]
8080 is a fairly common local-use HTTP port and it would be good to make this configurable to avoid conflicts with other applications or other users.

**Comment by goktug97** [comment]
https://github.com/org-roam/org-roam-server/blob/a3eeab95ba70e4df6abcfaf0a39f423f6954152a/org-roam-server.el#L70-L73
https://github.com/org-roam/org-roam-server/commit/a3eeab95ba70e4df6abcfaf0a39f423f6954152a
It is customizable now.
