### ISSUE TITLE
Node preview produces "500 Internal Error"

### ISSUE THREAD

**Issue by nalhasan** [org-roam/org-roam-server#20]
Hello,

For some reason when I enable the preview of OR notes I get the following error:

"error: (wrong-type-argument stringp nil)"

Any idea how I can go about debugging this issue?

Thank you!

**Comment by hyan46** [comment]
I got exactly the same issue here. I tried on both my Ubuntu computer and Mac Computer. Both have the same issues. Not sure what happened. The org-protocol works perfectly fine for me on both computers (So I can click on the node and go to the corresponding document). Also, I used doom emacs in both setup.

**Comment by goktug97** [comment]
I think it is an error related to the `org-journal`.  You can verify this by enabling debug on error with `toggle-debug-on-error` and exporting an org file to html manually which will show you stringp nil error is traced back to the org journal. On my Arch machine this is not an issue but in an Ubuntu machine I got the same error as yours. To fix this you need to uninstall the org-journal

**Comment by nalhasan** [comment]
You're right, deleting org-journal fixed the problem. Thank you!

**Comment by hyan46** [comment]
Confirm it is working! Thanks. Uninstall Org-journal since not using it too much.
