### ISSUE TITLE
is it possible to select multi notes, and then show other related notes which connect the selected notes at the same time

### ISSUE THREAD

**Issue by xiaolaoc** [org-roam/org-roam-server#23]

**Comment by qlibp** [comment]
i think it is a cool feature but maybe quite a lot work to do?

**Comment by xiaolaoc** [comment]
> i think it is a cool feature but maybe quite a lot work to do?

yes, it's not easy. I think this function can help to find relationship among the notes. Besides, i still hope it can add the function that if we select two(or even more) it can show all the passway which connect the selected notes, and I think by doing so, we can easily to get the core of the zettelkasten system-connection.

**Comment by goktug97** [comment]
Unfortunately, I won't implement this for now. I think if you are choosing several notes to find meaningful connection between them, you already decided what should connect to what. At that point I think you can parse it by just looking at them.
