### ISSUE TITLE
Node-color documentation

### ISSUE THREAD

**Issue by matthew-piziak** [org-roam/org-roam-server#25]
I'd like to categorize my nodes and have `org-roam-server`'s database display reflect that categorization with the colors of the nodes. The problem is that I can't tell what _currently_ governs the color. 

A note about that in the README would be much appreciated, even if it's just a reference to a dependency. Thank you!

**Comment by goktug97** [comment]
Nodes are grouped depending on their connections and currently there is no way to change that in the user side.

https://github.com/org-roam/org-roam-server/blob/c69d0f07fdc2465f987fe0a6b427a83e316e8212/index.html#L579-L598

**Comment by matthew-piziak** [comment]
Thank you!!

I updated the streamlet like so:
```
(defservlet* roam-data text/event-stream (force)
  (let* ((node-query `[:select [titles:file titles:titles tags:tags]
                       :from titles
                       :left :join tags
                       :on (= titles:file tags:file)
                       ,@(org-roam-graph--expand-matcher 'file t)
                       ])
         (data (org-roam-server-visjs-json node-query)))
    (when (or force (not (string= data org-roam-server-data)))
      (setq org-roam-server-data data)
      (insert (format "data: %s\n\n" org-roam-server-data)))))
```

And then pulled them out in `org-roam-server-visjs-json` like this:
```
… (tags (caddr (elt nodes idx)))
```
