### ISSUE TITLE
Preview stops after code in SRC area is evaluated

### ISSUE THREAD

**Issue by sharefantasy** [org-roam/org-roam-server#27]
Hi,
I come up with an issue with org-babel. When I try to preview an org file with SRC area inside, emacs ask me to evaluate the code. whether I choose evaluate or not, it won't show the preview in the browser.

condition:
1. emacs 27
2. org-roam-server: updated at 2020-06-03
3. SRC code type: plantuml
4. browse: chrome

Thank you!

P.S: Is the browser you are using in the README an emacs-embedded one?

**Comment by goktug97** [comment]
Does manually exporting the said org file to HTML work?

It is Firefox running in [EAF](https://github.com/manateelazycat/emacs-application-framework)

**Comment by sharefantasy** [comment]
> Does manually exporting the said org file to HTML work?
> 
> It is Firefox running in [EAF](https://github.com/manateelazycat/emacs-application-framework)

Well... I would rather not evaluate it. So I disable the preview for now.
I'll try EAF. Thanks!

**Comment by goktug97** [comment]
Added a new feature, the images are now shown in the viewer and previews.

In the case of plantuml I suggest adding

```
#+PROPERTY: header-args :eval never-export
```
to the org file so it won't be evaluated every time the preview is rendered. Eval using `C-c C-c`. 

If the images are too big it might halt.
