### ISSUE TITLE
[Feature Request] How about making custom css theme interface?

### ISSUE THREAD

**Issue by qlibp** [org-roam/org-roam-server#32]
Is it possible to make a interface for custom css? So that we could achieve the [following](https://forum.obsidian.md/t/andy-matuschak-mode-v2/170), when browsing files in file viewer. For now, we could merely scan through a file but not able to see multiple files all at once.

**Comment by goktug97** [comment]
added `org-roam-server-style` custom variable which can be used to customize the application (not just the iframes).

**Comment by qlibp** [comment]
I am going to try this out! Thx!
