### ISSUE TITLE
Significant db update upstream

### ISSUE THREAD

**Issue by zaeph** [org-roam/org-roam-server#33]
We're about to push a significant change to the db upstream with org-roam/org-roam/pull/783, more specifically [renaming the link-types](https://github.com/org-roam/org-roam/pull/783/commits/2cac9fbe40e7c71853ea95c20e308abddc3b4ebd).

You might want to pin Org-roam until you've addressed it.

**Comment by goktug97** [comment]
Thank you for the heads up! I didn't see any changes that might affect org-roam-server but to make sure, I pulled the changes (1.1.2) and tested it. Everything is working perfectly so far.

**Comment by zaeph** [comment]
All good, then. :)
