### ISSUE TITLE
Open org files in another buffer

### ISSUE THREAD

**Issue by takuyozora** [org-roam/org-roam-server#34]
Thanks for your project, it's really awesome !

I would like to have the same behavior as the gif in your readme : when I click on a node I would like to open it in another buffer, not in the current one (the EAF browser buffer).

It's not the case from scratch, so have you done some modifications in your EAF config to make it possible ?

**Comment by goktug97** [comment]
The EAF in the gif is the stock version, no changes have been made. I don’t use EAF, opened it for the purpose of demonstration. 
One way to reproduce what you want is, open an org roam file, open EAF in another buffer. It should open the clicked node in the buffer with the org roam file.

**Comment by takuyozora** [comment]
I've tried different setup, but the one with EAF didn't work has excepted for me.
Nevertheless I now use a custom qutebrowser config and it works like a charm.

Thanks.
