### ISSUE TITLE
Each click on a node opens a new Emacs frame with a maybe "legit" link but NOT opening the corresponding buffer.

### ISSUE THREAD

**Issue by herop** [org-roam/org-roam-server#35]
What I want to achieve:
org-roam-server should load corresponding window / frame

What I have:

Windows10

- Emacs 27.096 Win-client
- Installed org-roam org-roam-server and require org-roam protocol
- Standard config from manual pages org-roam
- Calling org-roam-server-mode works fine and shows anything I want it to show
- Even “Database”, “Buffer” view automatically follows my buffers in the emacs client

Issue:

- Each click on a node in the 127.0.0.1:8080 page opens a new frame of Emacs
- And tries to open a file from the wrong path like so: c:/Program Files (x86)/Microsoft/Edge Dev/Application/85.0.538.0/org-protocol:/roam-file/?file=c%3A%2FUsers%2FJochenBurkhard%2FiCloudDrive%2FiCloud~com~appsonthemove~beorg%2Forg%2F2020-06-04.org

Thank you in advance for your insight and support and greetings,
Jochen

![image](https://user-images.githubusercontent.com/658323/84510619-a5e4ee00-acc5-11ea-83e4-b8059924583c.png)

![image](https://user-images.githubusercontent.com/658323/84510745-d036ab80-acc5-11ea-98b0-6031430e0174.png)

**Comment by goktug97** [comment]
I have this problem too, haha :D 

I have tested with org-roam-graph to see if it is specific to the org-roam-server and the same problem appears in there too. So, I thought the problem is in my computer and as I don’t use clicking feature that much I didn’t spend any time to fix it. 

@jethrokuan @zaeph @TimQuelch 
Do you have any idea why it might be happening?

**Comment by jethrokuan** [comment]
What's the corresponding `org-protocol` path in `org-roam-server`? The graph generated works for me.

**Comment by goktug97** [comment]
I think I found the issue. The problem is org-protocol is not initialized correctly and maybe not initialized at all. I was using 

use-package org-roam-protocol :after org-protocol

I changed it to require ‘org-roam-protocol which fixed the problem. 

@herop can you check your configuration?

P.S. I am accessing to the Github from the phone so sorry for the bad formatting

**Comment by herop** [comment]
Thank you @goktug97, but I use require already...
** Org-roam-server
#+begin_src emacs-lisp
(use-package org-roam-server
  :ensure t
  :config
  (setq org-roam-server-host "127.0.0.1"
        org-roam-server-port 8080
        org-roam-server-export-inline-images t
        org-roam-server-authenticate nil
        org-roam-server-label-truncate t
        org-roam-server-label-truncate-length 60
        org-roam-server-label-wrap-length 20))
#+end_src
** Org-roam-protocol
#+begin_src emacs-lisp
(require 'org-roam-protocol)
#+end_src
#

**Comment by goktug97** [comment]
Can you also test org-roam-graph to see if org-protocol is initialized correctly

**Comment by herop** [comment]
I don't use / have an org-roam-graph-executable at all. 
And why is it needed, if anything is accordingly rendered via the web-browser and reacts to my buffer changes and even an my click?
I'm confused...

**Comment by herop** [comment]
I didn't forget your question though @jethrokuan.
But don't know how to pull up this information?!?
Don't forget that I'm on windows...

**Comment by goktug97** [comment]
org-roam-graph is org-roam’s built in graph generator which utilizes graphviz. If org-roam-graph doesn’t work too, we can conclude that the issue is not just specific to the org-roam-server.

**Comment by herop** [comment]
👌.  But what can I do now?

**Comment by goktug97** [comment]
> 👌. But what can I do now?

Install graphviz and set org-roam-graph—executable, and test org-roam-graph

**Comment by herop** [comment]
Would have been nice to find anything in the org-roam documents mentioning graphviz. I even can't find out, what the name of the binary to put in the path is...

**Comment by goktug97** [comment]
> Would have been nice to find anything in the org-roam documents mentioning graphviz. I even can't find out, what the name of the binary to put in the path is...

https://org-roam.github.io/org-roam/manual/Graphing.html#Graphing

**Comment by herop** [comment]
Niiice, @goktug97 1, @herop 0 haha.
One more thing though:
* I managed to put the path to gvedit.exe (which might be right (but no hints in the docu :-)
* By calling org-roam-graph, gvedit opens with numerous empty and at any later call this is showing:
![image](https://user-images.githubusercontent.com/658323/84523258-50660c80-acd8-11ea-92b5-87b9bd3c11fb.png)
I hate it to bother you guys with my noob approach but something might not be right here don't you think?

**Comment by goktug97** [comment]
No worries. 

https://ci.appveyor.com/api/buildjobs/92iav81dkovdrv4o/artifacts/build%2FGraphviz-install.exe

You should look for the `dot` executable. The gvedit is probably a viewer. In org-roam, the dot executable is called with cmd args `-Tsvg` and as the `gvedit` doesn't have those, it fails. The correct executable is `dot`

**Comment by herop** [comment]
Progress - sort of:
* A huge *.svg file is opened in my active window (after calling org-roam-graph)
* What's next?

**Comment by goktug97** [comment]
The SVG file should be clickable if you are talking about your browser's active window if not please open the svg file in your browser and click any of nodes to see if it opens the note in your emacs

> Let me say this: Your immediate help is immensely appreciated and the org-server package is shockingly great!!

Thank you!

**Comment by herop** [comment]
I should have said: In my active Emacs window :-(
Try to figure out how to open it in the browser...
But what is the right way to do it?
I thought:
* Click on the browser node
* Emacs should open a window in the existing frame - showing the corresponding note
What is wrong with this approach and why are you pointing me to graphviz at all?
To me that is confusing...
Again: The browser is working fine with all the fancy graphics globally and per buffer.
Only clicking on a node won't work.

**Comment by goktug97** [comment]
You can open a file in your browser by typing its location to the address bar. For example `file:///tmp/graph.c1uZWE.svg`

The same protocol is used in both `org-roam-graph` and `org-roam-server` to open the corresponding file in Emacs. If it doesn't work like the `org-roam-server`, it means that the problem is not releated to the `org-roam-server` but something different.

**Comment by herop** [comment]
Ok. But that sounds like a huge effort and why not going the other way round (my way)
* Opening the server browser window on 127.0.0.1:8080
* Browsing the current buffer and opening the buffer from there?
Btw.: What is the real meaning and how to use the "Enable preview" button?

**Comment by goktug97** [comment]
>Opening the server browser window on 127.0.0.1:8080
Browsing the current buffer and opening the buffer from there?

Because this is the issue. It doesn't work in your setup. By checking if your setup is working in native graph generation you are ensuring that your setup is configured correctly. If it doesn't work it means the problem is not releated to the `org-roam-server` but to your setup.

If the preview is enabled, it shows the preview of the file when you hover on it.

**Comment by herop** [comment]
Ahh, ok. Today is not my "fast-thinker-day" I presume :-)
But Now this:
![image](https://user-images.githubusercontent.com/658323/84529702-32050e80-ace2-11ea-9a01-a62a7482daec.png)

**Comment by goktug97** [comment]
@jethrokuan I couldn't see any windows related installation instructions in [Org Roam Protocol](https://org-roam.github.io/org-roam/manual/Installation-_00281_0029.html#Installation-_00281_0029). Does `org-roam-protocol` work in Windows?

**Comment by herop** [comment]
Ahh, something went wrong with the above file. 
But now I managed to open it. Sorry
![image](https://user-images.githubusercontent.com/658323/84530315-3847ba80-ace3-11ea-88fc-1eb9fde5d3bb.png)
This is, what the *Messages* buffer reads:
<snip>
Use M-x make-directory RET RET to create the directory and its parents
Problems while trying to load feature ‘ol-gnus’
Problems while trying to load feature ‘ol-eww’
Package cl is deprecated
</snip>

**Comment by jethrokuan** [comment]
The setup instructions for windows is here: https://orgmode.org/worg/org-contrib/org-protocol.html#org124a1fc

**Comment by goktug97** [comment]
> The setup instructions for windows is here: [orgmode.org/worg/org-contrib/org-protocol.html#org124a1fc](https://orgmode.org/worg/org-contrib/org-protocol.html#org124a1fc)

@herop Did you follow these intructions?

**Comment by herop** [comment]
- [X] Installation
- [X] Windows-Setup
- [ ] Browser (Not yet, try to wrap my head around the "Manual")...

**Comment by goktug97** [comment]
It should work without the browser configuration. Can you also share your configuration related to the org-roam and the org-roam-server

**Comment by herop** [comment]
Absolutely:
* Org-Server
** Start Server
#+begin_src emacs-lisp
(server-start)
(add-to-list 'load-path "~/org/")
(require 'org-protocol)
#+end_src
* Org-Roam
** Installation
#+begin_src emacs-lisp
        (use-package org-roam
              :hook
              (after-init . org-roam-mode)
              :custom
              (org-roam-directory "~/org/")
              :bind (:map org-roam-mode-map
                      (("C-c n l" . org-roam)
                       ("C-c n f" . org-roam-find-file)
                       ("C-c n j" . org-roam-jump-to-index)
                       ("C-c n b" . org-roam-switch-to-buffer)
		           ("C-c n i" . org-roam-insert)
                       ("C-c n t" . org-roam-dailies-today)
                       ("C-c n y" . org-roam-dailies-yesterday)
                       ("C-c n w" . org-roam-dailies-tomorrow)
                       ("C-c c" . org-roam-capture))))
#+end_src
** Configuration
#+begin_src emacs-lisp
      (setq org-todo-keywords
            '((sequence "TODO(t)" "NEXT(n)" "PROJECT(p)" "WAIT(w@/!)" "|" "DONE(d!)" "CANCELLED(c@)")))
    (setq org-roam-list-files-commands '(elisp))
      (setq org-roam-directory "~/org/")
      (setq org-roam-buffer-position 'left)
      (setq org-roam-buffer-width 0.15)
      (setq org-roam-link-title-format "R:%s")
      (setq org-roam-index-file "~/org/index.org")
      (setq org-roam-completion-system 'default)
      (setq org-roam-capture-templates
       '(("d" "default" plain (function org-roam--capture-get-point)
       "%?"
       :file-name "${slug}"
       :head "#+TITLE: ${title}\n#+CREATED: %<%Y-%m-%d>\n#+ROAM_ALIAS:\n#+ROAM_TAGS:\n\n* ${title}\n"
       :unnarrowed t)
        ))
  (setq org-roam-dailies-capture-templates
       '(("d" "daily" plain #'org-roam--capture-get-point ""
          :immediate-finish t
       :file-name "%<%Y-%m-%d>"
       :head "#+TITLE: ${title}\n#+CREATED: %<%Y-%m-%d>\n#+ROAM_ALIAS:\n#+ROAM_TAGS:\n\n* ${title}\n"
       :unnarrowed t)
        ))
#+end_src
** Org-roam-server
#+begin_src emacs-lisp
(use-package org-roam-server
  :ensure t
  :config
  (setq org-roam-server-host "127.0.0.1"
        org-roam-server-port 8080
        org-roam-server-export-inline-images t
        org-roam-server-authenticate nil
        org-roam-server-label-truncate t
        org-roam-server-label-truncate-length 60
        org-roam-server-label-wrap-length 20))
#+end_src

**Comment by herop** [comment]
Uhm, strikethrough lines should actually NOT occur!

**Comment by goktug97** [comment]
Did you forgot to include
```elisp
(require 'org-roam-protocol)
```
in above code? It does exist in your configuration, right?

**Comment by herop** [comment]
It is: Look at the very top: 
(server-start)
(add-to-list 'load-path "~/org/")
(require 'org-protocol)

**Comment by herop** [comment]
Aaaargh, wait: org-roam-protocol? Thought it would be org-protocol.

**Comment by herop** [comment]
Do I have to put both/only org-roam-protocol? I'm confused...

**Comment by goktug97** [comment]
Just put `(require 'org-roam-protocol)`

**Comment by herop** [comment]
Arghhh, this part is gone from my recent config.org. Hoooow come. Sit tight, I put it in again...

**Comment by herop** [comment]
Ok. DONE. 
* Opening org-roam-server-mode (127.0.0.1) CHECK
* Click a node from "Database Network"
* A NEW instance Emacs opens:
![image](https://user-images.githubusercontent.com/658323/84592808-97730f80-ae48-11ea-8527-81f164ade641.png)

**Comment by goktug97** [comment]
Remove `(server-start)` from your configuration, close Emacs, reopen Emacs, do `M-x server-start RET`, do `M-x org-roam-server-mode RET` and try again.

**Comment by herop** [comment]
Did it:
![image](https://user-images.githubusercontent.com/658323/84592959-91316300-ae49-11ea-82e5-f8a7fd5327f3.png)

**Comment by herop** [comment]
Clicked on this 2020-06-09 node you can see in bold.

**Comment by herop** [comment]
A new instance - again... :-(

**Comment by goktug97** [comment]
It is still in the *scratch* buffer. The buffer hasn't changed. Not even to the wrong one. Can you check if there is a buffer for your node. `C-x b`

**Comment by herop** [comment]
![image](https://user-images.githubusercontent.com/658323/84593020-f9804480-ae49-11ea-9a30-e820a637234d.png)

**Comment by herop** [comment]
Nope:
![image](https://user-images.githubusercontent.com/658323/84593052-2df40080-ae4a-11ea-84e7-efc1d6c00e88.png)

**Comment by goktug97** [comment]
You are opening runemacs.exe
It opens a new instance of Emacs, not Emacs that is connected to the server. It should be emacsclient.exe as shown in https://orgmode.org/worg/org-contrib/org-protocol.html#org124a1fc

**Comment by herop** [comment]
Ah, hold on: 
(org-roam) Upgrading the Org-roam database from version 5 to version 6
apply: Removing old name: Permission denied, c:/Users/JochenBurkhard/iCloudDrive/iCloud~com~appsonthemove~beorg/org/org-roam.db

**Comment by goktug97** [comment]
```
REGEDIT4

[HKEY_CLASSES_ROOT\org-roam-protocol]
@="URL:Org Roam Protocol"
"URL Protocol"=""
[HKEY_CLASSES_ROOT\org-roam-protocol\shell]
[HKEY_CLASSES_ROOT\org-roam-protocol\shell\open]
[HKEY_CLASSES_ROOT\org-roam-protocol\shell\open\command]
@="\"C:\\emacs-27.0.91-x86_64\\bin\\emacsclientw.exe\" \"%1\""

```

**Comment by herop** [comment]
Could not read org-id-values from ~/.emacs.d/.org-id-locations.  Setting it to nil.
(org-roam) files: 175, headlines: 1, links: 107, tags: 40, titles: 175, refs: 0, deleted: 0
Cleaning up the recentf list...done (0 removed)

**Comment by herop** [comment]
So, you're saying I need to replace runemacs.exe with emasclientw.exe, right?

**Comment by goktug97** [comment]
> So, you're saying I need to replace runemacs.exe with emasclientw.exe, right?

Yes

**Comment by herop** [comment]
![image](https://user-images.githubusercontent.com/658323/84593335-00a85200-ae4c-11ea-80af-54d01bdf94e8.png)

**Comment by goktug97** [comment]
Don't remove %1

**Comment by herop** [comment]
Error (having added %1)
![image](https://user-images.githubusercontent.com/658323/84593477-c12e3580-ae4c-11ea-89e4-b6bf9c7f9a7a.png)

**Comment by herop** [comment]
Notice, that I need to start Emacs like so:
![image](https://user-images.githubusercontent.com/658323/84593541-1e29eb80-ae4d-11ea-8470-316a1740e48f.png)

**Comment by herop** [comment]
That is what the --help option shows:
![image](https://user-images.githubusercontent.com/658323/84593611-4f0a2080-ae4d-11ea-8ad0-4528f0468b3b.png)

**Comment by herop** [comment]
Via emacsclient.exe or emacsclientw.exe, which allow you to invoke Emacs from other programs, and to reuse a running Emacs process for serving editing jobs required by other programs. See Emacs Server. The difference between emacsclient.exe and emacsclientw.exe is that the former is a console program, while the latter is a Windows GUI program.
(https://www.gnu.org/software/emacs/manual/html_node/emacs/Windows-Startup.html)

**Comment by herop** [comment]
From the desktop shortcut icon: either double-click the left mouse button on the icon, or click once, then press <RET>. The desktop shortcut should specify as its “Target” (in the “Properties” of the shortcut) the full absolute file name of runemacs.exe, not of emacs.exe. This is because runemacs.exe hides the console window that would have been created if the target of the shortcut were emacs.exe (which is a console program, as far as Windows is concerned).

**Comment by herop** [comment]
The straigh-process buffer reads:
$ cd "c:/emacs-27.0.91-x86_64/bin/"
$ "find" "/dev/null" "-newermt" "2018-01-01 12:00:00"

FIND: Invalid switch

[Return code: 2]

**Comment by herop** [comment]
Status:
![image](https://user-images.githubusercontent.com/658323/84593969-7e219180-ae4f-11ea-8f1d-9690335a39cc.png)
And:
![image](https://user-images.githubusercontent.com/658323/84593981-92fe2500-ae4f-11ea-9311-91c714a7f2cb.png)

**Comment by goktug97** [comment]
Replace emacsclientw with emacsclient
Close everything, restart your computer, open Emacs, do `M-x server-start RET`, do `M-x org-roam-server-mode`, open 127.0.0.1:8080, click to a node, it should open the file in your emacs

**Comment by herop** [comment]
It DOES! 
You're a magician!
Buuuut: for each click (which all worked btw.) Windows console windows where opened (and not closed unfortunately).
![image](https://user-images.githubusercontent.com/658323/84596092-ff7f2100-ae5b-11ea-9648-3888552f23e0.png)

**Comment by herop** [comment]
Same applies to using Brave.
Aaand, Emacs slows almost to a crawl. Even typing isn't fluent.

**Comment by goktug97** [comment]
I think you can close those terminal windows but I don't know about slowness and unfortunately it is not related to org-roam-server

**Comment by herop** [comment]
Yeah, I sure can. Tried it with no problems whatsoever.
Just thought, maybe there is some options to prevent them from opening altogether. :-)

Anyway: Let me provide a big shout-out for your unparalleled efforts and commitment to your loyal fans and community!
I never encountered anybody only remotely as supportive as you are!

You have more than deserved to call it a day and I will close this issue now.

**Comment by goktug97** [comment]
Unfortunately, it might be related to how Windows works. It might need to open up a terminal to execute a command.

>Let me provide a big shout-out for your unparalleled efforts and commitment to your loyal fans and community!
I never encountered anybody only remotely as supportive as you are!

Thank you!
