### ISSUE TITLE
Preview Mode – CC Mode is incompatible

### ISSUE THREAD

**Issue by matthew-piziak** [org-roam/org-roam-server#36]
Enabling Preview and mousing over a node yields the following:

># 500 Internal Error
>
>Internal error when handling this request.
>
>`error: (error CC Mode is incompatible with this version of Emacs - support for the ‘syntax-table’ text property is required.)`

I'm using Emacs 26.3 on NixOS. It looks like a problem with my Emacs but this is the only place I've seen it. I'm also surprised that CC Mode is even relevant here.

**Comment by goktug97** [comment]
Does File Viewer work? If not can you try to export the org file to HTML manually? `M-x org-export-dispatch RET h H`

**Comment by matthew-piziak** [comment]
After repulling and rebuilding all packages, issue does not persist. Thanks!
