### ISSUE TITLE
org-protocol-open-file not working

### ISSUE THREAD

**Issue by natask** [org-roam/org-roam-server#39]
org protocol was creating buffers pointing to %2path%2Fto%2Ffile.org. I  added `(setq file (org-link-decode file))` to `org-roam-protocol-open-file` to solve this issue.

**Comment by goktug97** [comment]
Are you sure the org-roam-protocol is set correctly? For example, if I use 
```elisp
(use-package org-roam-protocol
     :after org-protocol)
```
instead of
`(require ‘org-roam-protocol)`
I get the same issue as yours.

**Comment by natask** [comment]
I tried it but I am still getting the same issue. I thought it may be because I had also configured org-protocol with `require` and swapped that one with
``` elisp
(use-package org-protocol 
    :after org)
```
the error still persists.

I had looked this before and my understanding is that unless the incoming url is parsed for percent-encoded characters somewhere down the chain, the issue will persist. `org-protocol.el` of org-20200615 doesn't do this. Maybe there is a config variable I don't know of or my setup is incorrect some how.
 
For example, the following
``` js
//capture `p`
javascript:location.href = 'org-protocol://capture?template=p&url=' + encodeURIComponent(location.href) + '&title=' + encodeURIComponent(document.title || "[untitled page]") + '&body=' + encodeURIComponent(window.getSelection())
```
``` js
// capture `c`
javascript:location.href = 'org-protocol://capture?template=c&url=' + encodeURIComponent(location.href) + '&title=' + encodeURIComponent(document.title || "[untitled page]") + '&body=' + encodeURIComponent(window.getSelection())
```
working with
``` elisp
; to backup
(setq org-capture-templates-bak (copy-tree org-capture-templates))

; org-capture-templates
(setq org-capture-templates '(
("p" "Protocol Link" entry (file "/tmp/test_capture.org" ) 
"* %? [[%:link][%:description]] \nCaptured On: %U")
("c" "Protocol Link decoded" entry (file "/tmp/test_capture.org" ) 
"* %? [[%(org-link-decode \"%:link\")][%(org-link-decode \"%:description\")]] \nCaptured On: %U\n")
))

;to revert
(setq org-capture-templates (copy-tree org-capture-templates-bak))
(makunbound  org-capture-templates-bak)
```
capture `p` displays the same issue for me while capture `c` doesn't not.
can you check if it does so on your setup?

**Comment by goktug97** [comment]
Unfortunately and fortunately both templates work fine for me. I don't even load org-protocol. In my setup I only load org-roam-protocol. Can you try if it works for you by only loading org-roam-protocol? Maybe there is something happening there.

BTW if there is a confusion, I was using `use-package` to load the `org-roam-protocol` after the `org-protocol` and it didn't work for me so I revert it back to `(require 'org-roam-protocol)`

**Comment by michaelsjackson** [comment]
Maybe this helps in your case as well, worth trying at least, good luck.
https://github.com/org-roam/org-roam-server/issues/42

**Comment by natask** [comment]
@goktug97 org-roam-protocol requires org-protocol in its source code so sadly that is not going to work. 
@michaelsjackson my desktop file is the same as the one you are using

It seems to me that either has to do with my emacs version, org-protocol version or some configuration I have mistakenly changed. This is an upstream issue. At least there is a solution for now. There is an issue uptream [at](https://github.com/org-roam/org-roam/issues/860) documenting a similar problem.
Thanks for the hard work.

**Comment by goktug97** [comment]
> This is an upstream issue. At least there is a solution for now. There is an issue uptream documenting a similar problem.

I am closing this one then.

> Thanks for the hard work.

Thank you!

**Comment by natask** [comment]
turns out, it was a configuration issue. I was loading an archaic version of org.
