### ISSUE TITLE
Consider moving it into the org-roam team

### ISSUE THREAD

**Issue by jethrokuan** [org-roam/org-roam-server#4]
Hi! If you have intentions of keeping this maintained (I see you made a PR to melpa), do consider moving it into the org-roam team: https://github.com/org-roam

**Comment by goktug97** [comment]
Yes, of course, let's do it!

**Comment by jethrokuan** [comment]
Okay! Are you on Slack/Discourse? There's a lot of discussion on graphing at https://org-roam.discourse.group/c/dev/graph/8, was wondering if you had any input.

**Comment by goktug97** [comment]
I am not but I will join.

I think my implementation to group nodes is very basic and I think it can be more intelligent for the purpose of note-taking. I couldn't find a well-thought solution while researching as I haven't worked with graphs before.

**Comment by goktug97** [comment]
After closing this https://github.com/goktug97/org-roam-server/issues/2, will transfer to org-roam

**Comment by goktug97** [comment]
org-roam-server is now part of org-roam
