### ISSUE TITLE
[Feature request] directed graph

### ISSUE THREAD

**Issue by natask** [org-roam/org-roam-server#40]
Thanks for all the hard work. It will be nice to have an option to display forward links and backward links as separate edges connecting files. It makes it easier to figure out which file is the linking originating from.

**Comment by goktug97** [comment]
Would optional arrowheads work for you?

**Comment by natask** [comment]
that would be great.

**Comment by goktug97** [comment]
You can now enable arrows by setting the `org-roam-server-network-arrows` variable to `t`.

**Comment by natask** [comment]
awesome. checked it out. 
I felt that intuitively, I expected the direction to point from the file with the link to the file that is linked or forward links instead of backward links. Therefore, I replaced `(cons 'arrows "to")` with `(cons 'arrows "from")`. 
More generally, this can be made configurable with a variable `org-roam-server-network-arrows-back-link-direction` like so.
``` elisp
(if org-roam-server-network-arrows-back-link-direction
(cons 'arrows "to")
(cons 'arrows "from"))
```

**Comment by alanz** [comment]
> I felt that intuitively and as a default, I expected the direction to point from the file with the link to the file that is linked or forward links instead of backward links.

Agree

**Comment by goktug97** [comment]
Changed the option from boolean to string. Instead of setting `org-roam-network-arrows` to `t`, you can now set it to "to", "from", "middle", "to from", etc.

**Comment by alanz** [comment]
Perhaps you should set the customisation to be something like

```elisp
(defcustom org-roam-server-network-arrows "to"
  "If the type is given, enable arrows in the network.
Available types are to, middle, and from.
Types can be concatanated using commas."
  :group 'org-roam-server
  :type '(choice (const "to")
                 (const "from")
                 (const "to,from")
                 (const "middle")
                 string))
```

(note the default in current master is still `nil`?

**Comment by goktug97** [comment]
> Perhaps you should set the customisation to be something like
> 
> ```emacs-lisp
> (defcustom org-roam-server-network-arrows "to"
>   "If the type is given, enable arrows in the network.
> Available types are to, middle, and from.
> Types can be concatanated using commas."
>   :group 'org-roam-server
>   :type '(choice (const "to")
>                  (const "from")
>                  (const "to,from")
>                  (const "middle")
>                  string))
> ```
> 
> (note the default in current master is still `nil`?

While it would be less error prone, you can mix them anyway you want. For example, “to, middle” I don't think someone would want that but I don’t want some to open a issue like “make arrows more customizable” 😄 So I am not sure about this change.

I purposely left it as nil.
