### ISSUE TITLE
include file error in "file viewer"

### ISSUE THREAD

**Issue by Iorest** [org-roam/org-roam-server#41]
when I include a file using`#+INCLUDE`,there is an error `error: (error Cannot include file ~/.emacs.d/elpa/org-roam-server-20200608.1547/`,I don't konw how to solve it.

**Comment by goktug97** [comment]
I can't reproduce your error. 
`#+INCLUDE: "~/roam/agenda.org"`
This works perfectly fine for me. Maybe try updating everything to their the latest version.

Try exporting to the HTML manually to see if there is something wrong with your setup.

**Comment by Iorest** [comment]
Yes,sometimes it’s OK for me,and sometimes It‘s wrong.But I change nothing.I think there is a bug in directory setting.

**Comment by goktug97** [comment]
If you use relative paths, while exporting, it will use `org-roam-server` installation path as the root, not your roam-directory. You have to use absolute paths while using INCLUDE in your org files. I tried 
`#+INCLUDE: "~/test123.org"`
`#+INCLUDE: "/home/goktug/test123.org"`
and both works but 
`#+INCLUDE: "../test123.org"` doesn't work and I got 
`error: (error Cannot include file /home/goktug/libraries/test123.org)`

**Comment by Iorest** [comment]
Yeah，it‘s right！I’m confused how to solve it.

**Comment by goktug97** [comment]
Don't use relative paths, use full path of the file you want to include.
For example, dont use `#INCLUDE: test.org`, use `#INCLUDE: /home/lorest/roam-directory/test.org`.

**Comment by goktug97** [comment]
Do you have any update?

**Comment by goktug97** [comment]
Inactive
