### ISSUE TITLE
Clicking on links does not open the document in emacs, what can be wrong?

### ISSUE THREAD

**Issue by michaelsjackson** [org-roam/org-roam-server#42]
Here the connection from browser (firefox) to emacs does not work, what can be the reason?
Ubuntu 18.04, emacs 26.3, org-mode 9.3.6, firefox 76.0.1

**Comment by goktug97** [comment]
- Did you start the emacs server using `server-start`
- Did you configure `org-roam-protocol`

**Comment by michaelsjackson** [comment]
Thanks my friend for the response. Yes server is started.

This command works when run from terminal.
`emacsclient "org-protocol://roam-file?file=~/org-brain/zettelkasten.org"`

org-roam-protocol configuration, yes to some degree, meaning I have this in my .emacs:

```
(require 'org-roam-protocol)

(use-package org-roam-server
  :ensure t
  :config
  (setq org-roam-server-host "127.0.0.1"
        org-roam-server-port 8080
        org-roam-server-export-inline-images t
        org-roam-server-authenticate nil
        org-roam-server-label-truncate t
        org-roam-server-label-truncate-length 60
        org-roam-server-label-wrap-length 20))
```

But what I did not do yet, is what is described here
https://org-roam.readthedocs.io/en/master/roam_protocol/

```
Linux

Create a desktop application. I place mine in ~/.local/share/applications/org-protocol.desktop:

[Desktop Entry]
Name=Org-Protocol
Exec=emacsclient %u
Icon=emacs-icon
Type=Application
Terminal=false
MimeType=x-scheme-handler/org-protocol

Associate org-protocol:// links with the desktop application by running in your shell:

xdg-mime default org-protocol.desktop x-scheme-handler/org-protocol

```

I guess this is the missing part then?  Can report back here after trying this.  Thanks again, greetings to İstanbul!

**Comment by michaelsjackson** [comment]
Yess!  Reporting back. Success!  Thanks a lot, just doing above solved the issue.  Maybe this should be added to main page in info section somewhere at the top!
