### ISSUE TITLE
The links are not drawn

### ISSUE THREAD

**Issue by Ingvar33** [org-roam/org-roam-server#50]
If you set this parameter, the links are not shown.
`org-roam-server-network-arrows t`
It worked a few commits ago.

**Comment by goktug97** [comment]
It is changed https://github.com/org-roam/org-roam-server/commit/53558fd757c6e67174f6d148494072e88007afb1 to accept strings to make it more configurable as requested in https://github.com/org-roam/org-roam-server/issues/40#issuecomment-648478250.
You can set it to “to” if you want the old behavior. 

Options are;
- “to”
- “middle”
- “from”
- Any combination you like separated by commas, for example, “to, from”

**Comment by Ingvar33** [comment]
Thank you very much! It's an interesting feature.
