### ISSUE TITLE
[bug」config org-roam-server-port doesn't work

### ISSUE THREAD

**Issue by zombie110year** [org-roam/org-roam-server#51]
org-roam-server version: 20200624.1658

I have set

```elisp
(use-package org-roam-server
  :ensure t
  :config
  (setq org-roam-server-host "127.0.0.1"
        org-roam-server-port 18080
;; ...
```

but the server still listening `127.0.0.1:8080`。

**Comment by goktug97** [comment]
Due to a “bug” in emacs-web-server, sometimes you have to close the emacs to stop all servers or manually kill web server processes. Easiest solution would be restarting the emacs
https://github.com/skeeto/emacs-web-server/issues/23

**Comment by goktug97** [comment]
Inactive
