### ISSUE TITLE
Schemata update upstream for `titles`

### ISSUE THREAD

**Issue by zaeph** [org-roam/org-roam-server#53]
org-roam/org-roam/pull/908 has changed the way we treat `titles`: rather than storing all the possible titles for a file in a list, we isolate each of those in a different cell.

This might cause problem for Org-roam-server, as it did upstream, cf. org-roam/org-roam/issues/912.

**Comment by goktug97** [comment]
Hey, thank you so much for notifying me! I will look in to it

**Comment by goktug97** [comment]
Fixed: https://github.com/org-roam/org-roam-server/commit/20ba6ab940ed338a401c5833d8229070e1bb6b3b

**Comment by maikol-solis** [comment]
Hi! 

I can't still generate the graph in the server. 

My approach was
- Update to the latest version `org-roam` and `org-roam-server`
- Recreate the database with `C-u M-x org-roam-db-build-cache`. 

Before https://github.com/org-roam/org-roam/pull/908 I could see the server graph in the localhost (http://127.0.0.1:8080/) without problems. 

Now it show the buttons "Reload", "Enable preview", etc,  but not the graph.

**Comment by goktug97** [comment]
What do you get if you navigate to http://127.0.0.1:8080/roam-data?force=1

**Comment by maikol-solis** [comment]
> What do you get if you navigate to http://127.0.0.1:8080/roam-data?force=1

I got this

```
500 Internal Error

Internal error when handling this request.

error: (emacsql-error near line 25: no such column: files.file)
```

**Comment by goktug97** [comment]
Can you
- close Emacs
- remove org-roam.db

and try again

**Comment by maikol-solis** [comment]
I closed Emacs and deleted org-roam.db and the error persist.

**Comment by maikol-solis** [comment]
> Can you
> 
>     * close Emacs
> 
>     * remove org-roam.db
> 
> 
> and try again

I appreciate any pointers to create some debug info to see why I can't create the graph. 

Just for the record, I can create with the new schemata the svg graph with `org-roam-graph-show` 

Thanks.

**Comment by goktug97** [comment]
I changed  `files:file` to `titles:file`, can you try again?

**Comment by maikol-solis** [comment]
Awesome, it fixed the problem! 
Now the graph is working again!
Thank you very much.
