### ISSUE TITLE
file-viewer - backlink ids are getting prefixed with "/"

### ISSUE THREAD

**Issue by AloisJanicek** [org-roam/org-roam-server#54]
In file-viewer tab, in roam-buffer pane on the right, clicking on backlink results in "Not Found" error in preview pane on the left because the link ids are consistently getting prefixed with slash:

```
<a name="backlink" id="/20200619173004-something.org" href="javascript:void(0)">Something</a>
```
Toplevel file links inside `<h3>` tag don't have leading slash and are working correctly, opening file to the left file preview pane.

This is an issue with server elisp code but it wasn't immediately obvious to me what exactly is causing it.

**Comment by goktug97** [comment]
Does your org-roam and org-roam-server have the latest commits? My setup doesn't have this issue. I've updated everything recently and since then I haven't added any links. I tried adding a link with the recent updates and it doesn't have this issue either. Can you look in to it more?

**Comment by AloisJanicek** [comment]
I verified it with vanilla doom-emacs chemacs profile and I did `doom up` before I reported this issue. In this profile I have `org-roam` unpined and `org-roam-server` recipe points to this github repo.

So I am on org-roam 1574e0d and org-roam-server 20ba6ab. 
No other server is running and interfering, I tried it in "anonymous" browser window.

**Comment by goktug97** [comment]
what is your `org-roam-directory`, can you try with and without slash at the end

**Comment by AloisJanicek** [comment]
`(setq org-roam-directory "/home/alois/Dropbox/org/roam-life")`
I don't have slash at the end

**Comment by goktug97** [comment]
I think putting a slash at the end might be the solution

**Comment by AloisJanicek** [comment]
You are correct, slash at the end immediately solves this.
