### ISSUE TITLE
EmacSQL had an unhandled condition: "no such column: title"

### ISSUE THREAD

**Issue by chrislockard** [org-roam/org-roam-server#55]
**What I expected:**
Starting `org-roam-server-mode` in Emacs then navigating to localhost:8080 displays the org-roam-server graph.

**What actually happened:**
I started `org-roam-server-mode` in Emacs and receive the following error:
`EmacSQL had an unhandled condition: "near line 891: no such column: title"` 💥

**Details:**
Emacs: `27.0.91`
Configuration: `DooM`
OS: `Darwin/macOS`
Emacsql-version: `3.0.0`
emacsql-sqlite3-executable: `/usr/bin/sqlite3`

`org-roam` is working correctly in the same configuration.

The web application launches on localhost:8080, but does not display any org-roam contents.

My org-roam files are synced to Dropbox and all org-roam configuration points to the Dropbox folder containing them.

**Troubleshooting steps:**
1. Remove all org-roam and org-roam-server configuration, 
2. restart Emacs, verify all is working as expected
3. Add org-roam package and configuration, verify all is working as expected
4. Add org-roam-server package, restart Emacs, verify problem persists
5. Remove org-roam-server package
6. Remove org-roam.db, restart Emacs
7. Add org-roam-server package, restart Emacs, verify problem persists
8. Remove org-roam-server package, restart Emacs
9. Remove org-roam.db, org-roam files, set org-roam directory to new location, restart Emacs
10. Add org-roam-server package, restart Emacs, verify problem persists

**Comment by goktug97** [comment]
https://github.com/org-roam/org-roam-server/issues/53 Can you upgrade the `org-roam`. The DB structure is changed. `titles:titles` is removed. Now we have `titles:title`. It seems your `org-roam-server` is up to date but not the `org-roam`

**Comment by chrislockard** [comment]
This fixed it! Thank you!

For DooM users out there like myself, the solution is to add the following to your DooM's `packages.el`:

`(unpin! org-roam)`

Then run `doom sync && doom up`
