### ISSUE TITLE
Filtering by tags in org-roam-server does not work

### ISSUE THREAD

**Issue by sunnyhasija** [org-roam/org-roam-server#56]
The filter (at the bottom left of the server on 127.0.0.1:8080) in the "Database network view" supposedly takes input. When I type in the filter, it says "No Results Found", even though the tags exist in the roam files. 

Expected behavior - it should display nodes with that tag.

**Comment by goktug97** [comment]
What do you get when you execute the below snippet in the *scratch* buffer
```elisp
(require 'org-roam)
(let* ((node-query `[:select tags :from tags])
       (data (org-roam-db-query node-query)))
  (print data))
```

**Comment by sunnyhasija** [comment]
I get nil '[2 times]'

**Comment by goktug97** [comment]
Are you sure you are using the tags correctly. It seems the tags are not initialized in your database.

Example usage:

```org
#+ROAM_TAGS: test
```

**Comment by sunnyhasija** [comment]
I see! Yes, I do not have Roam Tags set up correctly, I just have 

`tags ::` 

I will make the changes and report back! Thank you so much for your quick help!
