### ISSUE TITLE
[Bug] emacsql-error "near line 13: no such column: files.file"

### ISSUE THREAD

**Issue by slondr** [org-roam/org-roam-server#57]
Just installed org-roam-server for the first time, the webpage loads but there's no content. All the drop-down menus are blank and no graph is displayed. In the console I see a 500 error being received on the roam-data API call. Delving into the httpd emacs messages, I found the error `emacsql-error "near line 13: no such column: files.file"` printed every time the page tried to query roam data.

**Comment by goktug97** [comment]
Can you update org-roam-server. It should be fixed in the latest commit.

**Comment by slondr** [comment]
I updated to the latest version to see if that fixed it, and now nothing loads at all; I just get "Not Found: The requested URL was not found on this server." when I visit 127.0.0.1:8080 in my browser

**Comment by goktug97** [comment]
Did you start the server

**Comment by slondr** [comment]
Yep

**Comment by slondr** [comment]
Restarting emacsdaemon a few times fixed the issue
