### ISSUE TITLE
[Feature request] Neighbourhood highlight on node clicking

### ISSUE THREAD

**Issue by forkrul** [org-roam/org-roam-server#59]
This might be interesting to get brief overviews of connected nodes on the main view: "once a node is clicked all nodes are greyed out except for first and second order connected nodes"

https://visjs.github.io/vis-network/examples/network/exampleApplications/neighbourhoodHighlight.html

![image](https://user-images.githubusercontent.com/190788/87531201-a7714f80-c691-11ea-89a0-93638170d20d.png)

**Comment by goktug97** [comment]
I thought about adding this but buffer view already establishes this so I am not going to add this
