### ISSUE TITLE
Trouble Setting up

### ISSUE THREAD

**Issue by theianjones** [org-roam/org-roam-server#6]
Hey! Thanks for putting this project together. 

Im trying to get this going and am running into some errors:

![Image 2020-05-11 at 3 54 47 PM](https://user-images.githubusercontent.com/4407263/81605682-d7edf200-939f-11ea-8186-7d3b94fa5013.png)

Im using doom emacs and this is the related config I have going:

```lisp
;; .doom.d/config.el
(setq org-roam-directory "~/Desktop/03-resources/org-roam")
(after! org-roam
  (setq org-roam-graph-viewer "/usr/bin/open")
  (setq org-roam-ref-capture-templates
        '(("r" "ref" plain (function org-roam-capture--get-point)
           "%?"
           :file-name "websites/${slug}"
           :head "#+TITLE: ${title}
#+ROAM_KEY: ${ref}
- source :: ${ref}"
           :unnarrowed t)))
  (setq org-roam-capture-templates
        '(("d" "default" plain (function org-roam--capture-get-point)
           "%?"
           :file-name "${slug}"
           :head "#+TITLE: ${title}\n"
           :unnarrowed t))))

(require 'simple-httpd)
(setq httpd-root "/var/www")
(httpd-start)

(use-package org-roam-server
  :ensure nil
  :load-path "~/Desktop/01-projects/org-roam-server/")
```

```lisp
;; .doom.d/init.el
(org +roam)
```

Do you have any suggestions on how to debug this?

**Comment by goktug97** [comment]
The org-roam recently updated (https://github.com/org-roam/org-roam/pull/547) and the database structure is changed a little bit. So updating the org-roam and rebuilding the database should fix that problem.

**Comment by d12frosted** [comment]
In case of doom, you might want to unpin `org-roam` package. Or pin to something newer.

**Comment by theianjones** [comment]
Thanks for the response, that got it working! This project is amazing and im super excited about it 🤩
