### ISSUE TITLE
Org-roam-server empty on Windows

### ISSUE THREAD

**Issue by Bassmann** [org-roam/org-roam-server#60]
I try to use org-roam-server on Windows but the resulting browser view is empty with a strange textbox at the left bottom edge
![grafik](https://user-images.githubusercontent.com/3171330/87592844-d36cef00-c6ea-11ea-84bd-7fc4166921fc.png)

Is Windows not supported or am I making a stupid mistake? My config is this:
(use-package org-roam-server
  :ensure t
  :config
  (setq org-roam-server-host "127.0.0.1"
        org-roam-server-port 8080
        org-roam-server-export-inline-images t
        org-roam-server-authenticate nil
        org-roam-server-network-poll t
        org-roam-server-network-arrows nil
        org-roam-server-network-label-truncate t
        org-roam-server-network-label-truncate-length 60
        org-roam-server-network-label-wrap-length 20))

**Comment by goktug97** [comment]
Can you open http:// 127.0.0.1:8080/roam-data?force=1 and tell me what you see

**Comment by Bassmann** [comment]
500 Internal Error

Internal error when handling this request.

error: (emacsql-error near line 77: no such column: files.file)

**Comment by goktug97** [comment]
Can you update org-roam-server. This is fixed in a recent commit

**Comment by Bassmann** [comment]
That fixed it. Thanks a lot!

**Comment by fkgruber** [comment]
I'm having the same in windows even after update.
The error I'm getting is different:

> (request
>  (date "Sat, 18 Jul 2020 18:11:38 GMT")
>  (address "127.0.0.1")
>  (get "/network-vis-options")
>  (headers
>   ("GET" "/network-vis-options?token=null" "HTTP/1.1")
>   ("Host" "127.0.0.1:8080")
>   ("User-Agent" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0")
>   ("Accept" "*/*")
>   ("Accept-Language" "en-US,en;q=0.5")
>   ("Accept-Encoding" "gzip, deflate")
>   ("X-Requested-With" "XMLHttpRequest")
>   ("Connection" "keep-alive")
>   ("Referer" "http://127.0.0.1:8080/")
>   ("Content" "")))
> (error 500
>        (wrong-type-argument number-or-marker-p
> 			    [utf-8-unix utf-8-dos utf-8-mac]))
> (hard-error
>  (wrong-type-argument number-or-marker-p
> 		      [utf-8-unix utf-8-dos utf-8-mac]))
>

**Comment by goktug97** [comment]
> wrong-type-argument number-or-marker-p

This looks like a problem with your setup. Do you manually byte-compile your files, if so can you remove byte compiled files and try again. You can try to reinstall org-roam, org-roam-server, emacs-web-server etc.

**Comment by fkgruber** [comment]
thanks,
it seems some package was creating conflict.  it is working now.
