### ISSUE TITLE
Does not respect .dir-locals.el

### ISSUE THREAD

**Issue by gluaxspeed** [org-roam/org-roam-server#61]
Org roam server mode does not respect the org-roam-directory variable set in a .dir-locals.el file. Example .dir-locals.el:
```elisp
((nil . ((eval . (setq-local org-roam-directory default-directory)))))
```

**Comment by goktug97** [comment]
Yes
https://github.com/org-roam/org-roam-server/issues/8

**Comment by gluaxspeed** [comment]
Ah whoops, didn't see that on that one. My bad.

**Comment by goktug97** [comment]
No probs. I’ve tried lots of things but couldn’t fix it. Probably I am missing something
