### ISSUE TITLE
Is that possible to use 3D render to view the nodes?

### ISSUE THREAD

**Issue by randomwangran** [org-roam/org-roam-server#62]
It might sound ridiculous.

Is that possible to use 3D render to view the nodes?

Imagine all those green dots are the org-roam's nodes. We can drag the
idea and create the idea in the 3D world.

![demo-3D-nodes - Copy](https://user-images.githubusercontent.com/8197831/87749083-a5101200-c7c5-11ea-9ec4-bd00b7c4c288.gif)

**Comment by goktug97** [comment]
Unfortunately, the network library only supports 2d networks.

**Comment by randomwangran** [comment]
Never mind @goktug97. 2D networks is already an effective way to interact with user's thoughts. 

I've been thinking about the use of 3D from the time I put the issue here. Maybe in the future, it is helpful if users use it with virtual reality. I've included this idea in my org-roam notes.

**Comment by randomwangran** [comment]
Gold to see other people implement this:

https://twitter.com/DharamKapila/status/1325931967335034890
