### ISSUE TITLE
MELPA installation fail

### ISSUE THREAD

**Issue by sharingtom** [org-roam/org-roam-server#64]
Hi,

I am trying to install org-roam-server via MELPA and the _use-package_ code in the [README.md](https://github.com/org-roam/org-roam-server#installation), but the installation fails. _org-roam-server_'s [MELPA page](https://melpa.org/#/org-roam-server) shows 20200715.1116, but Emacs seems to be looking for an outdated version:

`Error (use-package): Failed to install org-roam-server: https://melpa.org/packages/org-roam-server-20200705.1103.tar: Not found`

Emacs: 26.3
Spacemacs: 0.300 (develop branch)
OS: Windows 10

**Comment by goktug97** [comment]
Can you run “package-refresh-contents” and try again

**Comment by sharingtom** [comment]
Thanks! That worked. I'm new to Emacs, and didn't know I had to do that manually. (I'm now getting an EmacsSQL error, but it does not seem to be related to _org-roam-server_, so I'll keep digging.)

Thanks for the fast reply!
