### ISSUE TITLE
Suggestion: When exporting html pages, use org-roam-publish function to include backlink notes

### ISSUE THREAD

**Issue by nmartin84** [org-roam/org-roam-server#66]
Hey there - love the package! I was thinking it would be nice if your package included this function linked below to export backlink contents into the published html files. -> https://github.com/org-roam/org-roam/blob/06afa2772562b87c54f6f731a9e6cd42804c5970/doc/org_export.md#backlinks-and-contents

**Comment by goktug97** [comment]
Can you show a screenshot of it

**Comment by nmartin84** [comment]
![yYDZCbXPMf](https://user-images.githubusercontent.com/38045018/88335805-83e57f00-ccf9-11ea-9740-a6a915295187.png)

**Comment by goktug97** [comment]
Hmm. Doesn’t the backlink viewer enough in the file viewer tab?

**Comment by nmartin84** [comment]
I'll have to get back to you on that. I haven't upgraded my packages for the past week or so and wanted to re-test with the latest changes, but the update broke org-roam-server and i'm getting "wrong type argument: listp, sp-text-mode-emoticon-p". Let me get around this issue and i'll keep you posted.

**Comment by nmartin84** [comment]
Ok - fixed the odd argument error. 

For some reason backlinks have never worked in org-roam-server for me like they do in your preview, so I wasn't even aware this feature existed! We can close this out and i'll see if I can figure this out.

**Comment by flowersw** [comment]
I'm seeing ```wrong type argument: listp, sp-text-mode-emoticon-p``` as well. Just curious - what did the fix end up being for you @nmartin84 ? I'm new-ish to emacs

**Comment by nmartin84** [comment]
@flowersw - I believe it's how it's the way its handling links from the directory its called from. If I call org-roam-server from the root of my org-directory it'll run fine, but if I call it from a nested folder, it hoses something up and I get `wrong type argument: listp, sp-text-mode-emoticon-p` and I have to reload emacs to get it working again. Haven't had much time to mess with it.

**Comment by flowersw** [comment]
gotcha @nmartin84  - thx for the quick reply
