### ISSUE TITLE
Filtering by tags not working

### ISSUE THREAD

**Issue by sunnyhasija** [org-roam/org-roam-server#67]
After a recent update, the filtering of the tags is not working. 

When I use the ROAM_TAGS property, I am able to see the tags in my database, but when I select one of the tags, I am unable to use the collapse the network graph to only the files with that tag.

![org-roam-server-screenshot](https://user-images.githubusercontent.com/11377935/88443121-0bf48300-cde5-11ea-8655-722e44423d5f.png)
For Example, in the screenshot above, before the update, when I chose literature review, the graph would only show the 6 papers I have in my DB that are tagged as "literature review". Now it does not seem to do so. 

Please help, this was a killer feature of ORS that provided great value.

**Comment by goktug97** [comment]
Because it is added to the blacklist. Click blacklist button to change the mode to whitelist.

**Comment by sunnyhasija** [comment]
d'oh! 

Thanks @goktug97
