### ISSUE TITLE
Help with setting up org roam graph

### ISSUE THREAD

**Issue by vp275** [org-roam/org-roam-server#68]
Hi, 
Your org roam graph is setup in a beautiful way. Is there anyway you can help me understand how I can use a setup similar to yours?

**Comment by goktug97** [comment]
In the demo I am using EAF (https://github.com/manateelazycat/emacs-application-framework) to open the Firefox inside of the Emacs. I don't use it normally.

- I use `doom-molokai` theme.
- My font is `Hack`.

Other than that everything is default.

**Comment by vp275** [comment]
I got it. Thank you so much. I find this to be really useful for getting a bird eyes view. Cheers.
