### ISSUE TITLE
EmacSQL had an unhandled condition: "near line 71: no such column: titles"

### ISSUE THREAD

**Issue by KonVas** [org-roam/org-roam-server#69]
#### Steps to Reproduce
1. Load Emacs
2. `org-roam-server-mode`
3. `org-roam-server-open`

#### Expected Results
Org-roam graph in Chrome

#### Actual Results
1. EmacSQL had an unhandled condition: "near line 97: no such column: titles"
2. Server is running properly but no graph is created.

### Environment
- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin19.5.0, NS appkit-1894.50 Version 10.15.5 (Build 19F101))
 of 2020-06-07
- Framework: Doom
- Org: Org mode version 9.4 (nil @ /Users/konstantinos/.emacs.d/.local/straight/build/org-mode/)
- Org-roam: 1.2.0

**Comment by goktug97** [comment]
Can you update the org-roam-server
