### ISSUE TITLE
Filter Database View

### ISSUE THREAD

**Issue by theianjones** [org-roam/org-roam-server#7]
It would be awesome to have an input on the database view to filter the nodes by title (or some other attribute) and get all nodes connected to the input match.

**Comment by goktug97** [comment]
Awesome idea but instead of adding it to the database view, I think adding it to the buffer view might be more appropriate as it already shows the node and the connected nodes.

**Comment by goktug97** [comment]
I've just added it (https://github.com/org-roam/org-roam-server/commit/5c830dd937c7904d53200dcb869f68e9d3790870). You can try it.

**Comment by theianjones** [comment]
Awesome! Looking now.

**Comment by theianjones** [comment]
Thats great 👌 hits my usecase!
