### ISSUE TITLE
Middle arrows in opposite direction (to currently set)

### ISSUE THREAD

**Issue by HennadiiM** [org-roam/org-roam-server#76]
First of all, thanks for such awesome package!

History of an issue:
1. In my workflow I feel more logical to use "from" type of arrows
![2020-08-19_11-33-57](https://user-images.githubusercontent.com/40464033/90612939-611f8b00-e211-11ea-951f-2d1c78d3ad2e.jpg)
2. I more like middle arrows (because they don't overlap content)
3. I thought "from middle" get's me result I want (one middle arrow in the "from" direction), but I get this:
![2020-08-19_11-34-56](https://user-images.githubusercontent.com/40464033/90612713-19006880-e211-11ea-956d-0b6f9301932b.jpg)

So, how is it possible?

**Comment by goktug97** [comment]
> First of all, thanks for such awesome package!

Thank you!!

Probably it won't work but can you try
"middle: {scaleFactor: 1}"

**Comment by HennadiiM** [comment]
> > First of all, thanks for such awesome package!
> 
> Thank you!!
> 
> Probably it won't work but can you try
:))
> "middle: {scaleFactor: -1}"
So, I have: `org-roam-server-network-arrows "middle: {scaleFactor: -1}"`
And the result isn't expected:
![2020-08-19_13-56-59](https://user-images.githubusercontent.com/40464033/90626565-cda38580-e223-11ea-9309-ea1e5d7b1a04.jpg)

**Comment by goktug97** [comment]
Is it working? :D

**Comment by HennadiiM** [comment]
> Is it working? :D

aha)

Not as I expected. I expected 1 middle arrow in the opposite direction.
And, yeah, it's working, my emacs doesn't crash :))

**Comment by goktug97** [comment]
Did you remove "from"?

**Comment by HennadiiM** [comment]
> Did you remove "from"?

Yep.

Furthermore, I tried to add it a few ago. It also doesn't solve situation (it gives me 3 arrows)

**Comment by goktug97** [comment]
Maybe the browser is caching it somehow, can you restart your computer and try again?

**Comment by HennadiiM** [comment]
> > Probably it won't work but can you try
> 
> :))
> 
> > "middle: {scaleFactor: -1}"
> 
> So, I have: `org-roam-server-network-arrows "middle: {scaleFactor: -1}"`
> And the result isn't expected:
> ![2020-08-19_13-56-59](https://user-images.githubusercontent.com/40464033/90626565-cda38580-e223-11ea-9309-ea1e5d7b1a04.jpg)

I've restarted my computer. All the same as I wrote above. Still 2 arrows (I want just one), still in the "wrong" direction.

**Comment by goktug97** [comment]
This should work
```elisp
(setq org-roam-server-network-arrows "middle")
(setq org-roam-server-network-vis-options
      (json-encode
       (list (cons 'edges
           (list (cons 'arrows
               (list (cons 'middle
                   (list (cons 'scaleFactor -1))))))))))
```

**Comment by HennadiiM** [comment]
Yeah! It works. 

Thanks for help and for link
