### ISSUE TITLE
Just text in network nodes

### ISSUE THREAD

**Issue by HennadiiM** [org-roam/org-roam-server#78]
Hi there,
One more time thanks for incredible package. It feels more and more powerful with time for me

So is it possible to get rid of circles in nodes and leave there just note's name?
Because for me circles looks more like a distraction.

**Comment by 20jam** [comment]
I think, I'm not sure but it could be achieved by editing the css file.

**Comment by goktug97** [comment]
You can set `shape` of the nodes to `box` and lower `opacity` to `0` using
```Elisp
(setq org-roam-server-extra-node-options (list (cons 'shape "box") (cons 'opacity 0.0)))
```

**Comment by HennadiiM** [comment]
> You can set `shape` of the nodes to `box` and lower `opacity` to `0` using
> 
> ```emacs-lisp
> (setq org-roam-server-extra-node-options (list (cons 'shape "box") (cons 'opacity 0.0)))
> ```

That's it. Thanks for reply!
