### ISSUE TITLE
wrong url in File Viewer > Backlink

### ISSUE THREAD

**Issue by husnoo** [org-roam/org-roam-server#80]
If I have a note A, in which I mention note B, I can go to note B and see the backlink to note A. However, the browser console indicates the call is being made to http://127.0.0.1:9000//A.html?token=null, where the double slash is causing this to return Not Found.

**Comment by husnoo** [comment]
Actually the link to A is fine, it's a second link in the backlinks entry to the same original note! 

So A ---> B. Open B, there's "1 Backlink" and two links under that: a link to A in bold then a link to B in normal font. The link to B is the broken one with two //. But this is not functionally required, unless I'm missing something?

**Comment by goktug97** [comment]
- I created new test database and changed `org-roam-directory` to `~/test-db/`
- Populated the db with new files
```bash
mkdir ~/test-db
echo "#+title: A\n[[file:B.org][B]]" > ~/test-db/A.org
echo "#+title: B" > ~/test-db/B.org
```
- Opened emacs and started the `org-roam-server`
- Opened `File Viewer`, navigated to A and clicked to B and then clicked to B in the backlinks

Everything works fine. Can you change your `org-roam-directory` from `~/data/markor` to `~/data/markor/` maybe it makes a difference

**Comment by husnoo** [comment]
Aha it does work now! Doesn't make a huge amount of sense though, does it? Adding a slash in .emacs stops it from adding two slashes in the link.... oh well, software. Thank you!

**Comment by goktug97** [comment]
> Aha it does work now! Doesn't make a huge amount of sense though, does it? Adding a slash in .emacs stops it from adding two slashes in the link.... oh well, software. Thank you!

In `file:/home/test/Directory/file.org` `file:org-roam-directory` is replaced by `server:` when you don't have a slash at the end it becomes `server:/file.org`. If you have an ending slash it becomes `server:file.org` which is the correct one. 
Fixed: https://github.com/org-roam/org-roam-server/commit/aa605958a154b2133a98ebcbb42099b4fadf75f7
It doesn't matter now if you have an ending slash or not.
