### ISSUE TITLE
Forward slash in org protocol links are removed which prevents emacs to open file

### ISSUE THREAD

**Issue by abailly** [org-roam/org-roam-server#81]
*Disclaimer*: I have just started using org-roam and org-roam-server so I might be doing something. I am on Mac OS X Catalina and I have configured org-protocol handler (I can capture hyperlinks from Chrome using extension). When I start org-roam-server, it works fine and I can browse the graph of notes, and when I click on a node it opens the link using org-protocol but the URL seems to be incorrectly encoded or interpreted: The forward slashes are encoded à `%2F` but those are replaced by the word `Emacs` in Emacs. 
For example, clicking on this node:
<img width="377" alt="Screenshot 2020-09-06 at 09 01 40" src="https://user-images.githubusercontent.com/40221/92320152-ae786680-f01f-11ea-8fdb-f15acf671fa5.png">
opens this buffer in Emacs:
<img width="768" alt="Screenshot 2020-09-06 at 09 01 52" src="https://user-images.githubusercontent.com/40221/92320162-b9cb9200-f01f-11ea-8f4f-7f06bb86f901.png">

What am I doing wrong?

**Comment by goktug97** [comment]
Just to make sure it is not related to the latest commit, can you load `org-roam-server` from the folder with the 74957d0afdf11706797a058ffb2fb417e6036775 commit. 

```bash
git clone https://github.com/org-roam/org-roam-server ~/org-roam-server
cd org-roam-server
git checkout 74957d0afdf11706797a058ffb2fb417e6036775
```

and in your config file;
```elisp
(use-package org-roam-server
  :ensure nil
  :after org-roam
  :load-path "~/org-roam-server/")
```

**Comment by abailly** [comment]
Thanks for the suggestion:
* Same issue with the given commit,
* `org-roam-graph` has the same problem.
Might be an issue with org-protocol handler?

**Comment by goktug97** [comment]
Yes, it is an issue with how org-protocol is set up but unfortunately I don't have any pointers for how to solve it

**Comment by abailly** [comment]
I am stupid: I was missing `(require 'org-roam-protocol)` in my .emacs
