### ISSUE TITLE
Could not install org-roam-server

### ISSUE THREAD

**Issue by roiholtzman** [org-roam/org-roam-server#82]
I tried to install as written in the documentation, but I got the following error:

`
Error (use-package): Failed to install org-roam-server: https://melpa.org/packages/org-roam-server-20200822.1054.tar: Not found
Error (use-package): Cannot load org-roam-server
`

Why can't it be found on `melpa`?

**Comment by goktug97** [comment]
You need to run package-refresh-contents

**Comment by roiholtzman** [comment]
Thanks! that worked!
