### ISSUE TITLE
Wrong type argument: listp, sp-text-mode-emoticon-p

### ISSUE THREAD

**Issue by lewisliuyi** [org-roam/org-roam-server#84]
When I M-x "org-roam-server-mode", emacs always prompts "Wrong type argument: listp, sp-text-mode-emoticon-p".If I click on the node on the web page, the content cannot be previewed.I think it is a small problem, I use doom emacs. But I don’t know in which file the error of this setting appears

**Comment by goktug97** [comment]
I think it is related to smartparens https://github.com/org-roam/org-roam-server/issues/75#issuecomment-672070399

**Comment by lewisliuyi** [comment]
OK, maybe something wrong with doom. Thanks for your work!
