### ISSUE TITLE
using =verbatim= in org file is show in dark font even in dark mode when previewing notes in firefox

### ISSUE THREAD

**Issue by roiholtzman** [org-roam/org-roam-server#85]
First - I am using this package for two days and it's great! I love it!

The issue is that I have some org notes with `=verbatim=` in them. When previewing them in dark mode, the text is also dark so it is hard to read. 
Anyway to configure this?

**Comment by goktug97** [comment]
A little bit hacky but it works;
```elisp
(require 's)
(setq org-roam-server-export-style
      (s-replace ":not(pre)>code{padding:2px 5px;margin:auto 1px;border:1px solid #ddd;border-radius:3px;background-clip:padding-box;color:#333;font-size:80%}"
                 ":not(pre)>code{padding:2px 5px;margin:auto 1px;border:1px solid #ddd;border-radius:3px;background-clip:padding-box;color:white;font-size:80%}"
                 org-roam-server-export-style))
```

**Comment by roiholtzman** [comment]
Thanks! I tried that, but I still get dark font on dark background....
<img width="159" alt="Screen Shot 2020-09-14 at 9 37 40" src="https://user-images.githubusercontent.com/7188052/93052048-1ce7a500-f66e-11ea-8078-38c83f3757c8.png">

**Comment by goktug97** [comment]
Your browser might be caching it. Can you try with a different browser

**Comment by roiholtzman** [comment]
You're right!
It works!
