### ISSUE TITLE
[Feature request] Can I filter out dailies in the graph?

### ISSUE THREAD

**Issue by forkrul** [org-roam/org-roam-server#86]
Just again restating how amazingly useful I find this layer on top of org-roam. I use it for reviews, connecting notes, visual search of concepts, and absolutely cannot live without this (the last two months). 

Previously I've only used roam for notes, but recently I've started using the dailys (in future called daily scratch, I think). Backlinking in the dailies, create a lot of visual overlay cruft, that I think might be unnecessarily obfuscating connections (unless you're visually interested in _when_ you were working on key notes/concepts).

**Feature request:** I'd like to be able to filter out dailies and their backlinks from the graph, as a setup configuration variable. 

My logic for this is, I track my day, todos, supplement intake etc, via the dailies. If the daily backlinks get displayed in the graph, the time aspect and timeline inadvertently gets pulled into the graph. All dailies go to /dailies (for me), and they have non-standard naming (no -{slug} component).

**Comment by goktug97** [comment]
I think you can use ROAM_TAGS and default filters for that. A capture template can be added to dailies so it automatically tags them with #+ROAM_TAGS: Dailies
and default filter can be set using 

(setq org-roam-server-default-exclude-filters (json-encode (list (list (cons 'id "Dailies") (cons 'parent "tags")))))

https://github.com/org-roam/org-roam-server/issues/77

**Comment by forkrul** [comment]
That's not even something I considered, thanks for the idea. 

I've included this in my literate conf. 
` Org-roam dailies
Separate out the dailies into their own folder, add a dailies tag for filtering from visuals.

#+BEGIN_SRC emacs-lisp
(setq org-roam-dailies-capture-templates '(("d" "daily" plain (function org-roam-capture--get-point) ""
                                            :immediate-finish t
                                            :file-name "dailies/%<%Y-%m-%d>"
                                            :head "#+TITLE: %<%Y-%m-%d>\n#+ROAM_TAGS: Dailies")))
#+END_SRC
`
as well as injected the proposed header into the dailies. 

On doom/sync + emacs --debug-init, no errors pop up. 

However, I see the following when starting M-x org-roam-server:
`Org-Roam-Server mode disabled
-contains?: Wrong type argument: listp, sp-text-mode-emoticon-p`

Did I mess up the syntax or something else?

**Comment by forkrul** [comment]
That's not something I considered, thanks. Works like a charm :)
