### ISSUE TITLE
The graph is cluttered such that the titles cannot be read - is there any way of spreading out the graph automatically?

### ISSUE THREAD

**Issue by roiholtzman** [org-roam/org-roam-server#90]
Here is how my graph looks like. Is there a way to spread it out automatically such that all the titles can be read easily?

<img width="291" alt="Screen Shot 2020-09-16 at 10 55 01" src="https://user-images.githubusercontent.com/7188052/93308567-1cd0dc00-f80b-11ea-888d-efca897cf82f.png">

**Comment by goktug97** [comment]
You can set node shape to box. The titles will be within the boxes.

(setq org-roam-server-extra-node-options (list (cons 'shape "box")))

**Comment by roiholtzman** [comment]
Nice:) 
But it is still cluttered... And the bright font is hard to read on the colored nodes.
I guess it is better to have without the box...

<img width="358" alt="Screen Shot 2020-09-16 at 13 31 21" src="https://user-images.githubusercontent.com/7188052/93326074-f453dc80-f820-11ea-9322-e3db9d654d4e.png">

**Comment by goktug97** [comment]
You can also set `avoidOverlap` in the physics but it might not converge to a stable position so all nodes might move constantly. 

```elisp
(setq org-roam-server-network-vis-options
      (json-encode
       (list
        (cons 'physics (list (cons 'barnesHut (list (cons 'avoidOverlap 0.1)))))
        (cons 'nodes (list (cons 'shape "box")
                           (cons 'font (list (cons 'color "white"))))))))
```

This is the only solution I can come up with

**Comment by roiholtzman** [comment]
That works quite well! Thanks!
