### ISSUE TITLE
Performance impact on actual buffer editing after save

### ISSUE THREAD

**Issue by forkrul** [org-roam/org-roam-server#91]
I've been having some minor performance issues lately (db reached 4k+ notes). 

![image](https://user-images.githubusercontent.com/190788/93595739-91954900-f9b8-11ea-8397-d9e965e4eaba.png)

**Issue:** shortly after saving, I sometimes get a .5-multisecond delay as I wait for the graph to refresh. This shouldn't be the case on a machine with 16 cores, and significant free RAM. 

When turning off org-roam-server, the lag disappears. Something is either locking, or there is a bottleneck I can't seem to find. 

Looking at the image above, the httpd server does not run in it's own process. Would it be possible to fork this off, so it could potentially be reniced? Other ideas? Polling impact?

**Comment by goktug97** [comment]
Can you try disabling auto updates to see if it makes any difference

**Comment by roiholtzman** [comment]
I also experience lagging due to `org-roam-server`. How should I disable the auto updates?

**Comment by goktug97** [comment]
> I also experience lagging due to `org-roam-server`. How should I disable the auto updates?

```elisp
(setq org-roam-server-network-poll nil)
```

**Comment by forkrul** [comment]
Let me play with that and see if the lagging continues, thanks for the variable pointer.

**Comment by forkrul** [comment]
Played around with this for a week, day on, day off. It does seem to be polling. Can the process be forked off, so one can enable polling but nice it, so it doesn't affect the editor?

**Comment by goktug97** [comment]
Unfortunately, as far as I know, every process in emacs runs in a single core, so every process locks emacs. But checking database updates can be improved so I will look into that.

**Comment by goktug97** [comment]
It should be better now. It will only create the json format if the database is modified. You can still disable the polling but `org-roam` only updates the database if your emacs is idling or if you run `org-roam-db-build-cache`, so enabling polling should not affect your usage of the emacs now.
https://github.com/org-roam/org-roam-server/commit/608fc3865ff1c69c9802d2e2bb22430e83252c3c

**Comment by forkrul** [comment]
Thanks a lot. This sounds promising, waiting for idle.
