### ISSUE TITLE
org-roam-db--get removed from org-roam-20201005.1056 on melpa

### ISSUE THREAD

**Issue by Scrofff** [org-roam/org-roam-server#99]
The function org-roam-db--get has been removed from the current version of org-roam. There is now a custom variable org-roam-db-location which does the same job - adding the function definition below to my init.el let org-roam-server work correctly

(defun org-roam-db--get () org-roam-db-location)

**Comment by goktug97** [comment]
Fixed
https://github.com/org-roam/org-roam-server/pull/98
https://github.com/org-roam/org-roam-server/commit/1dc94e102d60e53bb9929b1cdc55d4d8c2b0d64f
